/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Govereau, Sean McLaughlin
*/
#pragma once

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "stdc.h"
#include "region.h"
#include "ast_common.h"
#include "ast_python_core.h"
#include "ast_nki.h"
#include "ast_klir.h"

// KLR File Formats

struct Serde_KLRFile {
  u32 major;
  u32 minor;
  u32 patch;
};

struct Serde_KLRMetaData {
  char *format;
};

enum File_Contents_Tag {
  File_Contents_python = 1,
  File_Contents_nki,
  File_Contents_kernel,
  File_Contents_lnc,
  File_Contents_hlo,
};
struct File_Contents_python {
  struct Python_Kernel *kernel;
};
struct File_Contents_nki {
  struct NKI_Kernel *kernel;
};
struct File_Contents_kernel {
  struct Core_Kernel *kernel;
};
struct File_Contents_lnc {
  struct Core_LncKernel *kernel;
};
struct File_Contents_hlo {
  char *name;
};
struct File_Contents {
  enum File_Contents_Tag tag;
  union {
    struct File_Contents_python python;
    struct File_Contents_nki nki;
    struct File_Contents_kernel kernel;
    struct File_Contents_lnc lnc;
    struct File_Contents_hlo hlo;
  };
};
