/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Written by the KLR Contributors (https://github.com/leanprover/KLR)
*/
#pragma once

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "klir_common.hpp"

namespace klr {

// KLR.Core Abstract Syntax

struct Pos final {
  Nat line;
  Nat column;
  Nat lineEnd;
  Nat columnEnd;
};

enum class Memory {
  hbm = 1,
  sbuf,
  pmem,
  reg,
};

enum class Dtype {
  bfloat16 = 1,
  float8e3,
  float8e4,
  float8e5,
  float16,
  float32,
  float32r,
  int8,
  int16,
  int64,
  int32,
  uint8,
  uint16,
  uint32,
  uint64,
};

struct Shape final {
  Nat parDim;
  List<Nat> freeDims;
};

struct Address final {
  Memory memory;
  Nat parSize;
  Nat freeSize;
  Nat parOffset;
  Nat freeOffset;
};

struct TensorSram final {
  String name;
  Dtype dtype;
  Ptr<Shape> shape;
  Ptr<Address> address;
  Prop parWF;
  Prop freeWF;
};

struct Slice final {
  Nat l;
  Nat u;
  Int step;
  Prop wf;
};

struct Index final {
  enum class Tag {
    coord = 1,
    slice,
  };
  struct Index_coord final {
    Nat e;
  };
  struct Index_slice final {
    Ptr<Slice> slice;
  };
  union U {
    U() {}
    ~U() {}
    Index_coord coord;
    Index_slice slice;
  };
  enum Tag tag;
  union U u;
  ~Index() {
    switch (tag) {
    case Tag::coord:
      u.coord.~Index_coord();
      break;
    case Tag::slice:
      u.slice.~Index_slice();
      break;
    }
  }
};

struct AccessBasic final {
  Ptr<TensorSram> tensor;
  List<Index> indexes;
  Prop lenWF;
};

struct APPair final {
  Int step;
  Nat num;
};

struct AccessPattern final {
  Ptr<TensorSram> tensor;
  Nat parNum;
  List<APPair> freePattern;
  Nat offset;
};

struct Access final {
  enum class Tag {
    simple = 1,
    basic,
    pattern,
  };
  struct Access_simple final {
    Ptr<TensorSram> tensor;
  };
  struct Access_basic final {
    Ptr<AccessBasic> access;
  };
  struct Access_pattern final {
    Ptr<AccessPattern> access;
  };
  union U {
    U() {}
    ~U() {}
    Access_simple simple;
    Access_basic basic;
    Access_pattern pattern;
  };
  enum Tag tag;
  union U u;
  ~Access() {
    switch (tag) {
    case Tag::simple:
      u.simple.~Access_simple();
      break;
    case Tag::basic:
      u.basic.~Access_basic();
      break;
    case Tag::pattern:
      u.pattern.~Access_pattern();
      break;
    }
  }
};

struct TensorHbm final {
  Dtype dtype;
  Nat address;
  List<Nat> shape;
  List<Nat> strides;
};

enum class ParQuadrant {
  par0 = 1,
  par32,
  par64,
  par96,
};

struct TensorView final {
  String name;
  Dtype dtype;
  ParQuadrant parQuadrant;
  Nat parDim;
  Nat freeOffset;
  List<APPair> freePattern;
};

struct TensorRef final {
  enum class Tag {
    abstract = 1,
    literal,
    reg,
  };
  struct TensorRef_abstract final {
    Ptr<Access> access;
  };
  struct TensorRef_literal final {
    Ptr<TensorView> view;
  };
  struct TensorRef_register final {
    Nat reg;
  };
  union U {
    U() {}
    ~U() {}
    TensorRef_abstract abstract;
    TensorRef_literal literal;
    TensorRef_register reg;
  };
  enum Tag tag;
  union U u;
  ~TensorRef() {
    switch (tag) {
    case Tag::abstract:
      u.abstract.~TensorRef_abstract();
      break;
    case Tag::literal:
      u.literal.~TensorRef_literal();
      break;
    case Tag::reg:
      u.reg.~TensorRef_register();
      break;
    }
  }
};

struct TensorArg final {
  enum class Tag {
    hbm = 1,
    sram,
  };
  struct TensorArg_hbm final {
    Ptr<TensorHbm> tensor;
  };
  struct TensorArg_sram final {
    Ptr<TensorSram> tensor;
  };
  union U {
    U() {}
    ~U() {}
    TensorArg_hbm hbm;
    TensorArg_sram sram;
  };
  enum Tag tag;
  union U u;
  ~TensorArg() {
    switch (tag) {
    case Tag::hbm:
      u.hbm.~TensorArg_hbm();
      break;
    case Tag::sram:
      u.sram.~TensorArg_sram();
      break;
    }
  }
};

enum class Engine {
  unassigned = 1,
  act,
  dma,
  dve,
  pe,
  pool,
  sp,
};

struct Immediate final {
  enum class Tag {
    reg = 1,
    pointer,
    int32,
    float32,
  };
  struct Immediate_register final {
    Nat reg;
  };
  struct Immediate_pointer final {};
  struct Immediate_int final {
    Int i;
  };
  struct Immediate_float final {
    Float f;
  };
  union U {
    U() {}
    ~U() {}
    Immediate_register reg;
    Immediate_pointer pointer;
    Immediate_int int32;
    Immediate_float float32;
  };
  enum Tag tag;
  union U u;
  ~Immediate() {
    switch (tag) {
    case Tag::reg:
      u.reg.~Immediate_register();
      break;
    case Tag::pointer:
      u.pointer.~Immediate_pointer();
      break;
    case Tag::int32:
      u.int32.~Immediate_int();
      break;
    case Tag::float32:
      u.float32.~Immediate_float();
      break;
    }
  }
};

struct ActivationImm final {
  enum class Tag {
    reg = 1,
    pointer,
    float32,
  };
  struct ActivationImm_register final {
    Nat reg;
  };
  struct ActivationImm_pointer final {};
  struct ActivationImm_float final {
    Float f;
  };
  union U {
    U() {}
    ~U() {}
    ActivationImm_register reg;
    ActivationImm_pointer pointer;
    ActivationImm_float float32;
  };
  enum Tag tag;
  union U u;
  ~ActivationImm() {
    switch (tag) {
    case Tag::reg:
      u.reg.~ActivationImm_register();
      break;
    case Tag::pointer:
      u.pointer.~ActivationImm_pointer();
      break;
    case Tag::float32:
      u.float32.~ActivationImm_float();
      break;
    }
  }
};

struct DataPattern final {
  Nat offset;
  List<APPair> pattern;
};

enum class AluOp {
  abs = 1,
  add,
  arith_shift_left,
  arith_shift_right,
  average,
  bitwise_and,
  bitwise_not,
  bitwise_or,
  bitwise_xor,
  bypass,
  divide,
  is_equal,
  is_ge,
  is_gt,
  is_le,
  is_lt,
  logical_and,
  logical_or,
  logical_shift_left,
  logical_shift_right,
  logical_xor,
  max,
  min,
  mod,
  mult,
  not_equal,
  pow,
  rsqrt,
  subtract,
};

enum class DropoutThresholdType {
  DropRate = 1,
  KeepRate,
};

enum class AccumCmd {
  Idle = 1,
  Zero,
  Accumulate,
  ZeroAccumulate,
  LoadAccumulate,
};

enum class ActivationFunc {
  abs = 1,
  arctan,
  copy,
  erf,
  erf_dx,
  exp,
  gelu,
  gelu_apprx_tanh,
  gelu_dx,
  log,
  mish,
  reciprocal,
  relu,
  rsqrt,
  sigmoid,
  sign,
  silu,
  silu_dx,
  sin,
  softplus,
  sqrt,
  square,
  tanh,
};

enum class AffineSelectCmp {
  GreaterThan = 1,
  GreaterThanEq,
  Eq,
  NotEq,
};

enum class DgeComputeOp {
  none = 1,
  add,
};

struct DmaBounds final {
  enum class Tag {
    disable = 1,
    enable,
    reg,
  };
  struct DmaBounds_disable final {};
  struct DmaBounds_enable final {};
  struct DmaBounds_reg final {
    Nat reg;
  };
  union U {
    U() {}
    ~U() {}
    DmaBounds_disable disable;
    DmaBounds_enable enable;
    DmaBounds_reg reg;
  };
  enum Tag tag;
  union U u;
  ~DmaBounds() {
    switch (tag) {
    case Tag::disable:
      u.disable.~DmaBounds_disable();
      break;
    case Tag::enable:
      u.enable.~DmaBounds_enable();
      break;
    case Tag::reg:
      u.reg.~DmaBounds_reg();
      break;
    }
  }
};

enum class MatmulGroupElement {
  first = 1,
  middle,
  last,
};

struct IndexMissBehavior final {
  enum class Tag {
    imm = 1,
    skip,
  };
  struct IndexMissBehavior_imm final {
    Ptr<Immediate> value;
  };
  struct IndexMissBehavior_skip final {};
  union U {
    U() {}
    ~U() {}
    IndexMissBehavior_imm imm;
    IndexMissBehavior_skip skip;
  };
  enum Tag tag;
  union U u;
  ~IndexMissBehavior() {
    switch (tag) {
    case Tag::imm:
      u.imm.~IndexMissBehavior_imm();
      break;
    case Tag::skip:
      u.skip.~IndexMissBehavior_skip();
      break;
    }
  }
};

enum class TensorScalarReverseOps {
  none = 1,
  first,
  second,
  both,
};

enum class TensorSubDim {
  X = 1,
  XY,
  XYZ,
  XYZW,
};

struct Dropout final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  DropoutThresholdType thresholdType;
  Ptr<Immediate> threshold;
};

struct Activate final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AccumCmd accumulatorCmd;
  ActivationFunc activationFunc;
  Ptr<Immediate> scale;
  Ptr<Immediate> bias;
  Ptr<Immediate> imm;
};

struct AffineSelect final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AffineSelectCmp fillMode;
  Nat fillReg;
  Ptr<DataPattern> maskPattern;
};

struct DmaCopy final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  DgeComputeOp compute_op;
  Ptr<DmaBounds> dstBoundsCheck;
  Ptr<DmaBounds> srcBoundsCheck;
};

struct DmaTranspose final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct Transpose final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct LoadMaskRegister final {
  Nat regNum;
};

struct Shuffle final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct MemSet final {
  Ptr<TensorRef> dst;
  Nat value;
  Nat count;
};

struct Iota final {
  Ptr<TensorRef> dst;
  Ptr<DataPattern> pattern;
};

struct LoadStationary final {
  Ptr<TensorRef> src;
  bool isTranspose;
};

struct MatMul final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> moving;
  MatmulGroupElement psumAccumulateFlag;
};

struct LocalGather final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<IndexMissBehavior> indexMissBehavior;
  bool freePoolBuffer;
};

struct RangeSelect final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AccumCmd reduceCommand;
  AluOp reduceOp;
  Float base;
  Float fillValue;
  AluOp compOp0;
  AluOp compOp1;
  Ptr<Immediate> bound0;
  Ptr<Immediate> bound1;
};

struct ScalarTensorTensor final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src0;
  Ptr<TensorRef> src1;
  AluOp op0;
  AluOp op1;
  TensorScalarReverseOps reverseOperands;
  Ptr<Immediate> imm0;
  AccumCmd accumulatorCmd;
};

struct CopyPredicated final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<TensorRef> predicate;
};

struct TensorTensorScan final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src0;
  Ptr<TensorRef> src1;
  AluOp op0;
  AluOp op1;
  TensorScalarReverseOps reverseOperands;
  Ptr<Immediate> imm0;
  AccumCmd accumulatorCmd;
};

struct MatchValueLoad final {
  Ptr<TensorRef> src;
};

struct FindIndex8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct MatchReplace8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Float replaceValue;
};

struct Max8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct BatchNormAggregate final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct BatchNormStats final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct Reciprocal final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct Copy final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  TensorSubDim opDim;
};

struct TensorReduce final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AluOp op;
  TensorSubDim opDim;
  bool negated;
};

struct Operator final {
  enum class Tag {
    Activate = 1,
    AffineSelect,
    BatchNormAggregate,
    BatchNormStats,
    Copy,
    CopyPredicated,
    DmaCopy,
    DmaTranspose,
    Dropout,
    FindIndex8,
    Iota,
    LoadMaskRegister,
    LoadStationary,
    LocalGather,
    MatMul,
    MatchReplace8,
    MatchValueLoad,
    Max8,
    MemSet,
    RangeSelect,
    Reciprocal,
    ScalarTensorTensor,
    Shuffle,
    TensorReduce,
    TensorTensorScan,
    Transpose,
  };
  struct Activate final {
    Ptr<Activate> op;
  };
  struct AffineSelect final {
    Ptr<AffineSelect> op;
  };
  struct BatchNormAggregate final {
    Ptr<BatchNormAggregate> op;
  };
  struct BatchNormStats final {
    Ptr<BatchNormStats> op;
  };
  struct Copy final {
    Ptr<Copy> op;
  };
  struct CopyPredicated final {
    Ptr<CopyPredicated> op;
  };
  struct DmaCopy final {
    Ptr<DmaCopy> op;
  };
  struct DmaTranspose final {
    Ptr<DmaTranspose> op;
  };
  struct Dropout final {
    Ptr<Dropout> op;
  };
  struct FindIndex8 final {
    Ptr<FindIndex8> op;
  };
  struct Iota final {
    Ptr<Iota> op;
  };
  struct LoadMaskRegister final {
    Ptr<LoadMaskRegister> op;
  };
  struct LoadStationary final {
    Ptr<LoadStationary> op;
  };
  struct LocalGather final {
    Ptr<LocalGather> op;
  };
  struct MatMul final {
    Ptr<MatMul> op;
  };
  struct MatchReplace8 final {
    Ptr<MatchReplace8> op;
  };
  struct MatchValueLoad final {
    Ptr<MatchValueLoad> op;
  };
  struct Max8 final {
    Ptr<Max8> op;
  };
  struct MemSet final {
    Ptr<MemSet> op;
  };
  struct RangeSelect final {
    Ptr<RangeSelect> op;
  };
  struct Reciprocal final {
    Ptr<Reciprocal> op;
  };
  struct ScalarTensorTensor final {
    Ptr<ScalarTensorTensor> op;
  };
  struct Shuffle final {
    Ptr<Shuffle> op;
  };
  struct TensorReduce final {
    Ptr<TensorReduce> op;
  };
  struct TensorTensorScan final {
    Ptr<TensorTensorScan> op;
  };
  struct Transpose final {
    Ptr<Transpose> op;
  };
  union U {
    U() {}
    ~U() {}
    Activate Activate;
    AffineSelect AffineSelect;
    BatchNormAggregate BatchNormAggregate;
    BatchNormStats BatchNormStats;
    Copy Copy;
    CopyPredicated CopyPredicated;
    DmaCopy DmaCopy;
    DmaTranspose DmaTranspose;
    Dropout Dropout;
    FindIndex8 FindIndex8;
    Iota Iota;
    LoadMaskRegister LoadMaskRegister;
    LoadStationary LoadStationary;
    LocalGather LocalGather;
    MatMul MatMul;
    MatchReplace8 MatchReplace8;
    MatchValueLoad MatchValueLoad;
    Max8 Max8;
    MemSet MemSet;
    RangeSelect RangeSelect;
    Reciprocal Reciprocal;
    ScalarTensorTensor ScalarTensorTensor;
    Shuffle Shuffle;
    TensorReduce TensorReduce;
    TensorTensorScan TensorTensorScan;
    Transpose Transpose;
  };
  enum Tag tag;
  union U u;
  ~Operator() {
    switch (tag) {
    case Tag::Activate:
      u.Activate.~Activate();
      break;
    case Tag::AffineSelect:
      u.AffineSelect.~AffineSelect();
      break;
    case Tag::BatchNormAggregate:
      u.BatchNormAggregate.~BatchNormAggregate();
      break;
    case Tag::BatchNormStats:
      u.BatchNormStats.~BatchNormStats();
      break;
    case Tag::Copy:
      u.Copy.~Copy();
      break;
    case Tag::CopyPredicated:
      u.CopyPredicated.~CopyPredicated();
      break;
    case Tag::DmaCopy:
      u.DmaCopy.~DmaCopy();
      break;
    case Tag::DmaTranspose:
      u.DmaTranspose.~DmaTranspose();
      break;
    case Tag::Dropout:
      u.Dropout.~Dropout();
      break;
    case Tag::FindIndex8:
      u.FindIndex8.~FindIndex8();
      break;
    case Tag::Iota:
      u.Iota.~Iota();
      break;
    case Tag::LoadMaskRegister:
      u.LoadMaskRegister.~LoadMaskRegister();
      break;
    case Tag::LoadStationary:
      u.LoadStationary.~LoadStationary();
      break;
    case Tag::LocalGather:
      u.LocalGather.~LocalGather();
      break;
    case Tag::MatMul:
      u.MatMul.~MatMul();
      break;
    case Tag::MatchReplace8:
      u.MatchReplace8.~MatchReplace8();
      break;
    case Tag::MatchValueLoad:
      u.MatchValueLoad.~MatchValueLoad();
      break;
    case Tag::Max8:
      u.Max8.~Max8();
      break;
    case Tag::MemSet:
      u.MemSet.~MemSet();
      break;
    case Tag::RangeSelect:
      u.RangeSelect.~RangeSelect();
      break;
    case Tag::Reciprocal:
      u.Reciprocal.~Reciprocal();
      break;
    case Tag::ScalarTensorTensor:
      u.ScalarTensorTensor.~ScalarTensorTensor();
      break;
    case Tag::Shuffle:
      u.Shuffle.~Shuffle();
      break;
    case Tag::TensorReduce:
      u.TensorReduce.~TensorReduce();
      break;
    case Tag::TensorTensorScan:
      u.TensorTensorScan.~TensorTensorScan();
      break;
    case Tag::Transpose:
      u.Transpose.~Transpose();
      break;
    }
  }
};

struct Value final {
  enum class Tag {
    var = 1,
    boolean,
    int32,
    float32,
    access,
  };
  struct Value_var final {
    String x;
  };
  struct Value_bool final {
    bool value;
  };
  struct Value_int final {
    Int value;
  };
  struct Value_float final {
    Float value;
  };
  struct Value_access final {
    Ptr<Access> a;
  };
  union U {
    U() {}
    ~U() {}
    Value_var var;
    Value_bool boolean;
    Value_int int32;
    Value_float float32;
    Value_access access;
  };
  enum Tag tag;
  union U u;
  ~Value() {
    switch (tag) {
    case Tag::var:
      u.var.~Value_var();
      break;
    case Tag::boolean:
      u.boolean.~Value_bool();
      break;
    case Tag::int32:
      u.int32.~Value_int();
      break;
    case Tag::float32:
      u.float32.~Value_float();
      break;
    case Tag::access:
      u.access.~Value_access();
      break;
    }
  }
};

struct Keyword final {
  String name;
  Ptr<Value> value;
};

struct Expr final {
  enum class Tag {
    value = 1,
    call,
  };
  struct Expr_value final {
    Ptr<Value> v;
  };
  struct Expr_call final {
    String f;
    List<Value> args;
    List<Keyword> kwargs;
  };
  union U {
    U() {}
    ~U() {}
    Expr_value value;
    Expr_call call;
  };
  enum Tag tag;
  union U u;
  ~Expr() {
    switch (tag) {
    case Tag::value:
      u.value.~Expr_value();
      break;
    case Tag::call:
      u.call.~Expr_call();
      break;
    }
  }
};

struct Stmt final {
  enum class Tag {
    ret = 1,
    assign,
    store,
  };
  struct Stmt_ret final {
    Ptr<Value> v;
  };
  struct Stmt_assign final {
    String x;
    Ptr<Expr> e;
  };
  struct Stmt_store final {
    Ptr<Access> dst;
    Ptr<Operator> op;
    List<Value> args;
  };
  union U {
    U() {}
    ~U() {}
    Stmt_ret ret;
    Stmt_assign assign;
    Stmt_store store;
  };
  enum Tag tag;
  union U u;
  ~Stmt() {
    switch (tag) {
    case Tag::ret:
      u.ret.~Stmt_ret();
      break;
    case Tag::assign:
      u.assign.~Stmt_assign();
      break;
    case Tag::store:
      u.store.~Stmt_store();
      break;
    }
  }
};

struct Kernel final {
  String name;
  List<TensorArg> inputs;
  List<TensorArg> outputs;
  List<Stmt> body;
};

struct Python_Kernel {};
struct NKI_Kernel {};

struct KLRFile final {
  Nat major;
  Nat minor;
  Nat patch;
};

struct KLRMetaData final {
  String format;
};

struct Contents final {
  enum class Tag {
    python = 1,
    nki,
    klir,
    hlo,
  };
  struct Contents_python final {
    Ptr<Kernel> kernel;
  };
  struct Contents_nki final {
    Ptr<Kernel> kernel;
  };
  struct Contents_klir final {
    Ptr<Kernel> kernel;
  };
  struct Contents_hlo final {
    String name;
  };
  union U {
    U() {}
    ~U() {}
    Contents_python python;
    Contents_nki nki;
    Contents_klir klir;
    Contents_hlo hlo;
  };
  enum Tag tag;
  union U u;
  ~Contents() {
    switch (tag) {
    case Tag::python:
      u.python.~Contents_python();
      break;
    case Tag::nki:
      u.nki.~Contents_nki();
      break;
    case Tag::klir:
      u.klir.~Contents_klir();
      break;
    case Tag::hlo:
      u.hlo.~Contents_hlo();
      break;
    }
  }
};
} // namespace klr
