/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Written by the KLR Contributors (https://github.com/leanprover/KLR)
*/
#pragma once

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "klir_common.hpp"

namespace klr {

// KLR.Core Abstract Syntax

struct Pos final {
  Nat line;
  Nat column;
  Option<Nat> lineEnd;
  Option<Nat> columnEnd;
};

enum class Memory {
  hbm = 1,
  sbuf,
  pmem,
  reg,
};

enum class Dtype {
  bfloat16 = 1,
  float8e3,
  float8e4,
  float8e5,
  float16,
  float32,
  float32r,
  int8,
  int16,
  int64,
  int32,
  uint8,
  uint16,
  uint32,
  uint64,
};

struct Shape final {
  Nat parDim;
  List<Nat> freeDims;
};

struct Address final {
  Memory memory;
  Nat parSize;
  Nat freeSize;
  Option<Nat> parOffset;
  Option<Nat> freeOffset;
};

struct TensorSram final {
  String name;
  Dtype dtype;
  Ptr<Shape> shape;
  Ptr<Address> address;
  Prop parWF;
  Prop freeWF;
};

struct Slice final {
  Nat l;
  Nat u;
  Int step;
  Prop wf;
};

struct Index {
  enum class Tag {
    coord = 1,
    slice,
  };
  Tag tag;
  Index(Tag tag) : tag(tag) {}
};

struct Index_coord final : Index {
  Nat e;
  Index_coord() : Index(Tag::coord) {}
};

struct Index_slice final : Index {
  Ptr<Slice> slice;
  Index_slice() : Index(Tag::slice) {}
};

struct AccessBasic final {
  Ptr<TensorSram> tensor;
  List<Ptr<Index>> indexes;
  Prop lenWF;
};

struct APPair final {
  Int step;
  Nat num;
};

struct AccessPattern final {
  Ptr<TensorSram> tensor;
  Nat parNum;
  List<Ptr<APPair>> freePattern;
  Nat offset;
};

struct Access {
  enum class Tag {
    simple = 1,
    basic,
    pattern,
  };
  Tag tag;
  Access(Tag tag) : tag(tag) {}
};

struct Access_simple final : Access {
  Ptr<TensorSram> tensor;
  Access_simple() : Access(Tag::simple) {}
};

struct Access_basic final : Access {
  Ptr<AccessBasic> access;
  Access_basic() : Access(Tag::basic) {}
};

struct Access_pattern final : Access {
  Ptr<AccessPattern> access;
  Access_pattern() : Access(Tag::pattern) {}
};

struct TensorHbm final {
  Dtype dtype;
  Nat address;
  List<Nat> shape;
  List<Nat> strides;
};

enum class ParQuadrant {
  par0 = 1,
  par32,
  par64,
  par96,
};

struct TensorView final {
  String name;
  Dtype dtype;
  ParQuadrant parQuadrant;
  Nat parDim;
  Nat freeOffset;
  List<Ptr<APPair>> freePattern;
};

struct TensorRef {
  enum class Tag {
    abstract = 1,
    literal,
    reg,
  };
  Tag tag;
  TensorRef(Tag tag) : tag(tag) {}
};

struct TensorRef_abstract final : TensorRef {
  Ptr<Access> access;
  TensorRef_abstract() : TensorRef(Tag::abstract) {}
};

struct TensorRef_literal final : TensorRef {
  Ptr<TensorView> view;
  TensorRef_literal() : TensorRef(Tag::literal) {}
};

struct TensorRef_register final : TensorRef {
  Nat reg;
  TensorRef_register() : TensorRef(Tag::reg) {}
};

struct TensorArg {
  enum class Tag {
    hbm = 1,
    sram,
  };
  Tag tag;
  TensorArg(Tag tag) : tag(tag) {}
};

struct TensorArg_hbm final : TensorArg {
  Ptr<TensorHbm> tensor;
  TensorArg_hbm() : TensorArg(Tag::hbm) {}
};

struct TensorArg_sram final : TensorArg {
  Ptr<TensorSram> tensor;
  TensorArg_sram() : TensorArg(Tag::sram) {}
};

enum class Engine {
  unassigned = 1,
  act,
  dma,
  dve,
  pe,
  pool,
  sp,
};

struct Immediate {
  enum class Tag {
    reg = 1,
    pointer,
    int32,
    float32,
  };
  Tag tag;
  Immediate(Tag tag) : tag(tag) {}
};

struct Immediate_register final : Immediate {
  Nat reg;
  Immediate_register() : Immediate(Tag::reg) {}
};

struct Immediate_pointer final : Immediate {
  Immediate_pointer() : Immediate(Tag::pointer) {}
};

struct Immediate_int final : Immediate {
  Int i;
  Immediate_int() : Immediate(Tag::int32) {}
};

struct Immediate_float final : Immediate {
  Float f;
  Immediate_float() : Immediate(Tag::float32) {}
};

struct ActivationImm {
  enum class Tag {
    reg = 1,
    pointer,
    float32,
  };
  Tag tag;
  ActivationImm(Tag tag) : tag(tag) {}
};

struct ActivationImm_register final : ActivationImm {
  Nat reg;
  ActivationImm_register() : ActivationImm(Tag::reg) {}
};

struct ActivationImm_pointer final : ActivationImm {
  ActivationImm_pointer() : ActivationImm(Tag::pointer) {}
};

struct ActivationImm_float final : ActivationImm {
  Float f;
  ActivationImm_float() : ActivationImm(Tag::float32) {}
};

struct DataPattern final {
  Nat offset;
  List<Ptr<APPair>> pattern;
};

enum class AluOp {
  abs = 1,
  add,
  arith_shift_left,
  arith_shift_right,
  average,
  bitwise_and,
  bitwise_not,
  bitwise_or,
  bitwise_xor,
  bypass,
  divide,
  is_equal,
  is_ge,
  is_gt,
  is_le,
  is_lt,
  logical_and,
  logical_or,
  logical_shift_left,
  logical_shift_right,
  logical_xor,
  max,
  min,
  mod,
  mult,
  not_equal,
  pow,
  rsqrt,
  subtract,
};

enum class DropoutThresholdType {
  DropRate = 1,
  KeepRate,
};

enum class AccumCmd {
  Idle = 1,
  Zero,
  Accumulate,
  ZeroAccumulate,
  LoadAccumulate,
};

enum class ActivationFunc {
  abs = 1,
  arctan,
  copy,
  erf,
  erf_dx,
  exp,
  gelu,
  gelu_apprx_tanh,
  gelu_dx,
  log,
  mish,
  reciprocal,
  relu,
  rsqrt,
  sigmoid,
  sign,
  silu,
  silu_dx,
  sin,
  softplus,
  sqrt,
  square,
  tanh,
};

enum class AffineSelectCmp {
  GreaterThan = 1,
  GreaterThanEq,
  Eq,
  NotEq,
};

enum class DgeComputeOp {
  none = 1,
  add,
};

struct DmaBounds {
  enum class Tag {
    disable = 1,
    enable,
    reg,
  };
  Tag tag;
  DmaBounds(Tag tag) : tag(tag) {}
};

struct DmaBounds_disable final : DmaBounds {
  DmaBounds_disable() : DmaBounds(Tag::disable) {}
};

struct DmaBounds_enable final : DmaBounds {
  DmaBounds_enable() : DmaBounds(Tag::enable) {}
};

struct DmaBounds_reg final : DmaBounds {
  Nat reg;
  DmaBounds_reg() : DmaBounds(Tag::reg) {}
};

enum class MatmulGroupElement {
  first = 1,
  middle,
  last,
};

struct IndexMissBehavior {
  enum class Tag {
    imm = 1,
    skip,
  };
  Tag tag;
  IndexMissBehavior(Tag tag) : tag(tag) {}
};

struct IndexMissBehavior_imm final : IndexMissBehavior {
  Ptr<Immediate> value;
  IndexMissBehavior_imm() : IndexMissBehavior(Tag::imm) {}
};

struct IndexMissBehavior_skip final : IndexMissBehavior {
  IndexMissBehavior_skip() : IndexMissBehavior(Tag::skip) {}
};

enum class TensorScalarReverseOps {
  none = 1,
  first,
  second,
  both,
};

enum class TensorSubDim {
  X = 1,
  XY,
  XYZ,
  XYZW,
};

struct Dropout final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  DropoutThresholdType thresholdType;
  Ptr<Immediate> threshold;
};

struct Activate final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AccumCmd accumulatorCmd;
  ActivationFunc activationFunc;
  Ptr<Immediate> scale;
  Ptr<Immediate> bias;
  Ptr<Immediate> imm;
};

struct AffineSelect final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AffineSelectCmp fillMode;
  Nat fillReg;
  Ptr<DataPattern> maskPattern;
};

struct DmaCopy final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  DgeComputeOp compute_op;
  Ptr<DmaBounds> dstBoundsCheck;
  Ptr<DmaBounds> srcBoundsCheck;
};

struct DmaTranspose final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct Transpose final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct LoadMaskRegister final {
  Nat regNum;
};

struct Shuffle final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct MemSet final {
  Ptr<TensorRef> dst;
  Nat value;
  Nat count;
};

struct Iota final {
  Ptr<TensorRef> dst;
  Ptr<DataPattern> pattern;
};

struct LoadStationary final {
  Ptr<TensorRef> src;
  Bool isTranspose;
};

struct MatMul final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> moving;
  MatmulGroupElement psumAccumulateFlag;
};

struct LocalGather final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<IndexMissBehavior> indexMissBehavior;
  Bool freePoolBuffer;
};

struct RangeSelect final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AccumCmd reduceCommand;
  AluOp reduceOp;
  Float base;
  Float fillValue;
  AluOp compOp0;
  AluOp compOp1;
  Ptr<Immediate> bound0;
  Ptr<Immediate> bound1;
};

struct ScalarTensorTensor final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src0;
  Ptr<TensorRef> src1;
  AluOp op0;
  AluOp op1;
  TensorScalarReverseOps reverseOperands;
  Ptr<Immediate> imm0;
  AccumCmd accumulatorCmd;
};

struct CopyPredicated final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<TensorRef> predicate;
};

struct TensorTensorScan final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src0;
  Ptr<TensorRef> src1;
  AluOp op0;
  AluOp op1;
  TensorScalarReverseOps reverseOperands;
  Ptr<Immediate> imm0;
  AccumCmd accumulatorCmd;
};

struct MatchValueLoad final {
  Ptr<TensorRef> src;
};

struct FindIndex8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct MatchReplace8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Float replaceValue;
};

struct Max8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct BatchNormAggregate final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct BatchNormStats final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct Reciprocal final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct Copy final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Option<TensorSubDim> opDim;
};

struct TensorReduce final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AluOp op;
  TensorSubDim opDim;
  Bool negated;
};

struct Operator {
  enum class Tag {
    activate = 1,
    affineSelect,
    batchNormAggregate,
    batchNormStats,
    copy,
    copyPredicated,
    dmaCopy,
    dmaTranspose,
    dropout,
    findIndex8,
    iota,
    loadMaskRegister,
    loadStationary,
    localGather,
    matMul,
    matchReplace8,
    matchValueLoad,
    max8,
    memSet,
    rangeSelect,
    reciprocal,
    scalarTensorTensor,
    shuffle,
    tensorReduce,
    tensorTensorScan,
    transpose,
  };
  Tag tag;
  Operator(Tag tag) : tag(tag) {}
};

struct Operator_activate final : Operator {
  Ptr<Activate> op;
  Operator_activate() : Operator(Tag::activate) {}
};

struct Operator_affineSelect final : Operator {
  Ptr<AffineSelect> op;
  Operator_affineSelect() : Operator(Tag::affineSelect) {}
};

struct Operator_batchNormAggregate final : Operator {
  Ptr<BatchNormAggregate> op;
  Operator_batchNormAggregate() : Operator(Tag::batchNormAggregate) {}
};

struct Operator_batchNormStats final : Operator {
  Ptr<BatchNormStats> op;
  Operator_batchNormStats() : Operator(Tag::batchNormStats) {}
};

struct Operator_copy final : Operator {
  Ptr<Copy> op;
  Operator_copy() : Operator(Tag::copy) {}
};

struct Operator_copyPredicated final : Operator {
  Ptr<CopyPredicated> op;
  Operator_copyPredicated() : Operator(Tag::copyPredicated) {}
};

struct Operator_dmaCopy final : Operator {
  Ptr<DmaCopy> op;
  Operator_dmaCopy() : Operator(Tag::dmaCopy) {}
};

struct Operator_dmaTranspose final : Operator {
  Ptr<DmaTranspose> op;
  Operator_dmaTranspose() : Operator(Tag::dmaTranspose) {}
};

struct Operator_dropout final : Operator {
  Ptr<Dropout> op;
  Operator_dropout() : Operator(Tag::dropout) {}
};

struct Operator_findIndex8 final : Operator {
  Ptr<FindIndex8> op;
  Operator_findIndex8() : Operator(Tag::findIndex8) {}
};

struct Operator_iota final : Operator {
  Ptr<Iota> op;
  Operator_iota() : Operator(Tag::iota) {}
};

struct Operator_loadMaskRegister final : Operator {
  Ptr<LoadMaskRegister> op;
  Operator_loadMaskRegister() : Operator(Tag::loadMaskRegister) {}
};

struct Operator_loadStationary final : Operator {
  Ptr<LoadStationary> op;
  Operator_loadStationary() : Operator(Tag::loadStationary) {}
};

struct Operator_localGather final : Operator {
  Ptr<LocalGather> op;
  Operator_localGather() : Operator(Tag::localGather) {}
};

struct Operator_matMul final : Operator {
  Ptr<MatMul> op;
  Operator_matMul() : Operator(Tag::matMul) {}
};

struct Operator_matchReplace8 final : Operator {
  Ptr<MatchReplace8> op;
  Operator_matchReplace8() : Operator(Tag::matchReplace8) {}
};

struct Operator_matchValueLoad final : Operator {
  Ptr<MatchValueLoad> op;
  Operator_matchValueLoad() : Operator(Tag::matchValueLoad) {}
};

struct Operator_max8 final : Operator {
  Ptr<Max8> op;
  Operator_max8() : Operator(Tag::max8) {}
};

struct Operator_memSet final : Operator {
  Ptr<MemSet> op;
  Operator_memSet() : Operator(Tag::memSet) {}
};

struct Operator_rangeSelect final : Operator {
  Ptr<RangeSelect> op;
  Operator_rangeSelect() : Operator(Tag::rangeSelect) {}
};

struct Operator_reciprocal final : Operator {
  Ptr<Reciprocal> op;
  Operator_reciprocal() : Operator(Tag::reciprocal) {}
};

struct Operator_scalarTensorTensor final : Operator {
  Ptr<ScalarTensorTensor> op;
  Operator_scalarTensorTensor() : Operator(Tag::scalarTensorTensor) {}
};

struct Operator_shuffle final : Operator {
  Ptr<Shuffle> op;
  Operator_shuffle() : Operator(Tag::shuffle) {}
};

struct Operator_tensorReduce final : Operator {
  Ptr<TensorReduce> op;
  Operator_tensorReduce() : Operator(Tag::tensorReduce) {}
};

struct Operator_tensorTensorScan final : Operator {
  Ptr<TensorTensorScan> op;
  Operator_tensorTensorScan() : Operator(Tag::tensorTensorScan) {}
};

struct Operator_transpose final : Operator {
  Ptr<Transpose> op;
  Operator_transpose() : Operator(Tag::transpose) {}
};

struct Value {
  enum class Tag {
    var = 1,
    boolean,
    int32,
    float32,
    access,
  };
  Tag tag;
  Value(Tag tag) : tag(tag) {}
};

struct Value_var final : Value {
  String x;
  Value_var() : Value(Tag::var) {}
};

struct Value_bool final : Value {
  Bool value;
  Value_bool() : Value(Tag::boolean) {}
};

struct Value_int final : Value {
  Int value;
  Value_int() : Value(Tag::int32) {}
};

struct Value_float final : Value {
  Float value;
  Value_float() : Value(Tag::float32) {}
};

struct Value_access final : Value {
  Ptr<Access> a;
  Value_access() : Value(Tag::access) {}
};

struct Keyword final {
  String name;
  Ptr<Value> value;
};

struct Expr {
  enum class Tag {
    value = 1,
    call,
  };
  Tag tag;
  Expr(Tag tag) : tag(tag) {}
};

struct Expr_value final : Expr {
  Ptr<Value> v;
  Expr_value() : Expr(Tag::value) {}
};

struct Expr_call final : Expr {
  String f;
  List<Ptr<Value>> args;
  List<Ptr<Keyword>> kwargs;
  Expr_call() : Expr(Tag::call) {}
};

struct Stmt {
  enum class Tag {
    ret = 1,
    assign,
    store,
  };
  Tag tag;
  Stmt(Tag tag) : tag(tag) {}
};

struct Stmt_ret final : Stmt {
  Ptr<Value> v;
  Stmt_ret() : Stmt(Tag::ret) {}
};

struct Stmt_assign final : Stmt {
  String x;
  Ptr<Expr> e;
  Stmt_assign() : Stmt(Tag::assign) {}
};

struct Stmt_store final : Stmt {
  Ptr<Access> dst;
  Ptr<Operator> op;
  List<Ptr<Value>> args;
  Stmt_store() : Stmt(Tag::store) {}
};

struct Kernel final {
  String name;
  List<Ptr<TensorArg>> inputs;
  List<Ptr<TensorArg>> outputs;
  List<Ptr<Stmt>> body;
};

struct KLRFile final {
  Nat major;
  Nat minor;
  Nat patch;
};

struct KLRMetaData final {
  String format;
};

struct Contents {
  enum class Tag {
    python = 1,
    nki,
    klir,
    hlo,
  };
  Tag tag;
  Contents(Tag tag) : tag(tag) {}
};

struct Contents_python final : Contents {
  Ptr<Kernel> kernel;
  Contents_python() : Contents(Tag::python) {}
};

struct Contents_nki final : Contents {
  Ptr<Kernel> kernel;
  Contents_nki() : Contents(Tag::nki) {}
};

struct Contents_klir final : Contents {
  Ptr<Kernel> kernel;
  Contents_klir() : Contents(Tag::klir) {}
};

struct Contents_hlo final : Contents {
  String name;
  Contents_hlo() : Contents(Tag::hlo) {}
};
} // namespace klr
