/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Written by the KLR Contributors (https://github.com/leanprover/KLR)
*/

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "klir_common.hpp"
#include "klir_serde.hpp"

namespace klr {

bool List_des(FILE *in, List<Bool> &x) { return true; }

bool List_des(FILE *in, List<Nat> &x) { return true; }

bool List_des(FILE *in, List<Int> &x) { return true; }

bool List_des(FILE *in, List<Float> &x) { return true; }

bool List_des(FILE *in, List<String> &x) { return true; }

bool Option_des(FILE *in, Option<Bool> &x) { return true; }

bool Option_des(FILE *in, Option<Nat> &x) { return true; }

bool Option_des(FILE *in, Option<Int> &x) { return true; }

bool Option_des(FILE *in, Option<Float> &x) { return true; }

bool Option_des(FILE *in, Option<String> &x) { return true; }

bool Pos_des(FILE *in, Ptr<Pos> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 100 || c != 0 || l != 4)
    return false;
  *x = static_cast<Pos *>(region_alloc(region, sizeof(**x)));
  if (!Nat_des(in, &(*x)->line))
    return false;
  if (!Nat_des(in, &(*x)->column))
    return false;
  if (!Option_des(in, &(*x)->lineEnd))
    return false;
  if (!Option_des(in, &(*x)->columnEnd))
    return false;
  return true;
}

bool Memory_des(FILE *in, Memory &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 110)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = Memory::hbm;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = Memory::sbuf;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = Memory::pmem;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = Memory::reg;
    break;
  default:
    return false;
  }
  return true;
}

bool Dtype_des(FILE *in, Dtype &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 111)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = Dtype::bfloat16;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = Dtype::float8e3;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = Dtype::float8e4;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = Dtype::float8e5;
    break;
  case 4:
    if (l != 0)
      return false;
    *x = Dtype::float16;
    break;
  case 5:
    if (l != 0)
      return false;
    *x = Dtype::float32;
    break;
  case 6:
    if (l != 0)
      return false;
    *x = Dtype::float32r;
    break;
  case 7:
    if (l != 0)
      return false;
    *x = Dtype::int8;
    break;
  case 8:
    if (l != 0)
      return false;
    *x = Dtype::int16;
    break;
  case 9:
    if (l != 0)
      return false;
    *x = Dtype::int64;
    break;
  case 10:
    if (l != 0)
      return false;
    *x = Dtype::int32;
    break;
  case 11:
    if (l != 0)
      return false;
    *x = Dtype::uint8;
    break;
  case 12:
    if (l != 0)
      return false;
    *x = Dtype::uint16;
    break;
  case 13:
    if (l != 0)
      return false;
    *x = Dtype::uint32;
    break;
  case 14:
    if (l != 0)
      return false;
    *x = Dtype::uint64;
    break;
  default:
    return false;
  }
  return true;
}

bool Shape_des(FILE *in, Ptr<Shape> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 112 || c != 0 || l != 2)
    return false;
  *x = static_cast<Shape *>(region_alloc(region, sizeof(**x)));
  if (!Nat_des(in, &(*x)->parDim))
    return false;
  if (!List_des(in, &(*x)->freeDims))
    return false;
  return true;
}

bool Address_des(FILE *in, Ptr<Address> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 113 || c != 0 || l != 5)
    return false;
  *x = static_cast<Address *>(region_alloc(region, sizeof(**x)));
  if (!Memory_des(in, &(*x)->memory))
    return false;
  if (!Nat_des(in, &(*x)->parSize))
    return false;
  if (!Nat_des(in, &(*x)->freeSize))
    return false;
  if (!Option_des(in, &(*x)->parOffset))
    return false;
  if (!Option_des(in, &(*x)->freeOffset))
    return false;
  return true;
}

bool TensorSram_des(FILE *in, Ptr<TensorSram> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 114 || c != 0 || l != 6)
    return false;
  *x = static_cast<TensorSram *>(region_alloc(region, sizeof(**x)));
  if (!String_des(in, &(*x)->name))
    return false;
  if (!Dtype_des(in, &(*x)->dtype))
    return false;
  if (!Shape_des(in, &(*x)->shape))
    return false;
  if (!Address_des(in, &(*x)->address))
    return false;
  if (!Prop_des(in, &(*x)->parWF))
    return false;
  if (!Prop_des(in, &(*x)->freeWF))
    return false;
  return true;
}

bool Slice_des(FILE *in, Ptr<Slice> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 115 || c != 0 || l != 4)
    return false;
  *x = static_cast<Slice *>(region_alloc(region, sizeof(**x)));
  if (!Nat_des(in, &(*x)->l))
    return false;
  if (!Nat_des(in, &(*x)->u))
    return false;
  if (!Int_des(in, &(*x)->step))
    return false;
  if (!Prop_des(in, &(*x)->wf))
    return false;
  return true;
}

bool Index_des(FILE *in, Ptr<Index> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 116)
    return false;
  *x = static_cast<Index *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Nat_des(in, &(*x)->coord.e))
      return false;
    (*x)->tag = Index_coord;
    break;
  case 1:
    if (l != 1)
      return false;
    if (!Slice_des(in, &(*x)->slice.slice))
      return false;
    (*x)->tag = Index_slice;
    break;
  default:
    return false;
  }
  return true;
}

bool AccessBasic_des(FILE *in, Ptr<AccessBasic> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 117 || c != 0 || l != 3)
    return false;
  *x = static_cast<AccessBasic *>(region_alloc(region, sizeof(**x)));
  if (!TensorSram_des(in, &(*x)->tensor))
    return false;
  if (!List_des(in, &(*x)->indexes))
    return false;
  if (!Prop_des(in, &(*x)->lenWF))
    return false;
  return true;
}

bool APPair_des(FILE *in, Ptr<APPair> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 118 || c != 0 || l != 2)
    return false;
  *x = static_cast<APPair *>(region_alloc(region, sizeof(**x)));
  if (!Int_des(in, &(*x)->step))
    return false;
  if (!Nat_des(in, &(*x)->num))
    return false;
  return true;
}

bool AccessPattern_des(FILE *in, Ptr<AccessPattern> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 119 || c != 0 || l != 4)
    return false;
  *x = static_cast<AccessPattern *>(region_alloc(region, sizeof(**x)));
  if (!TensorSram_des(in, &(*x)->tensor))
    return false;
  if (!Nat_des(in, &(*x)->parNum))
    return false;
  if (!List_des(in, &(*x)->freePattern))
    return false;
  if (!Nat_des(in, &(*x)->offset))
    return false;
  return true;
}

bool Access_des(FILE *in, Ptr<Access> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 120)
    return false;
  *x = static_cast<Access *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!TensorSram_des(in, &(*x)->simple.tensor))
      return false;
    (*x)->tag = Access_simple;
    break;
  case 1:
    if (l != 1)
      return false;
    if (!AccessBasic_des(in, &(*x)->basic.access))
      return false;
    (*x)->tag = Access_basic;
    break;
  case 2:
    if (l != 1)
      return false;
    if (!AccessPattern_des(in, &(*x)->pattern.access))
      return false;
    (*x)->tag = Access_pattern;
    break;
  default:
    return false;
  }
  return true;
}

bool TensorHbm_des(FILE *in, Ptr<TensorHbm> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 121 || c != 0 || l != 4)
    return false;
  *x = static_cast<TensorHbm *>(region_alloc(region, sizeof(**x)));
  if (!Dtype_des(in, &(*x)->dtype))
    return false;
  if (!Nat_des(in, &(*x)->address))
    return false;
  if (!List_des(in, &(*x)->shape))
    return false;
  if (!List_des(in, &(*x)->strides))
    return false;
  return true;
}

bool ParQuadrant_des(FILE *in, ParQuadrant &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 122)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = ParQuadrant::par0;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = ParQuadrant::par32;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = ParQuadrant::par64;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = ParQuadrant::par96;
    break;
  default:
    return false;
  }
  return true;
}

bool TensorView_des(FILE *in, Ptr<TensorView> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 123 || c != 0 || l != 6)
    return false;
  *x = static_cast<TensorView *>(region_alloc(region, sizeof(**x)));
  if (!String_des(in, &(*x)->name))
    return false;
  if (!Dtype_des(in, &(*x)->dtype))
    return false;
  if (!ParQuadrant_des(in, &(*x)->parQuadrant))
    return false;
  if (!Nat_des(in, &(*x)->parDim))
    return false;
  if (!Nat_des(in, &(*x)->freeOffset))
    return false;
  if (!List_des(in, &(*x)->freePattern))
    return false;
  return true;
}

bool TensorRef_des(FILE *in, Ptr<TensorRef> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 124)
    return false;
  *x = static_cast<TensorRef *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Access_des(in, &(*x)->abstract.access))
      return false;
    (*x)->tag = TensorRef_abstract;
    break;
  case 1:
    if (l != 1)
      return false;
    if (!TensorView_des(in, &(*x)->literal.view))
      return false;
    (*x)->tag = TensorRef_literal;
    break;
  case 2:
    if (l != 1)
      return false;
    if (!Nat_des(in, &(*x)->reg.reg))
      return false;
    (*x)->tag = TensorRef_register;
    break;
  default:
    return false;
  }
  return true;
}

bool TensorArg_des(FILE *in, Ptr<TensorArg> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 125)
    return false;
  *x = static_cast<TensorArg *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!TensorHbm_des(in, &(*x)->hbm.tensor))
      return false;
    (*x)->tag = TensorArg_hbm;
    break;
  case 1:
    if (l != 1)
      return false;
    if (!TensorSram_des(in, &(*x)->sram.tensor))
      return false;
    (*x)->tag = TensorArg_sram;
    break;
  default:
    return false;
  }
  return true;
}

bool Engine_des(FILE *in, Engine &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 130)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = Engine::unassigned;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = Engine::act;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = Engine::dma;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = Engine::dve;
    break;
  case 4:
    if (l != 0)
      return false;
    *x = Engine::pe;
    break;
  case 5:
    if (l != 0)
      return false;
    *x = Engine::pool;
    break;
  case 6:
    if (l != 0)
      return false;
    *x = Engine::sp;
    break;
  default:
    return false;
  }
  return true;
}

bool Immediate_des(FILE *in, Ptr<Immediate> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 131)
    return false;
  *x = static_cast<Immediate *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Nat_des(in, &(*x)->reg.reg))
      return false;
    (*x)->tag = Immediate_register;
    break;
  case 1:
    if (l != 0)
      return false;
    (*x)->tag = Immediate_pointer;
    break;
  case 2:
    if (l != 1)
      return false;
    if (!Int_des(in, &(*x)->int32.i))
      return false;
    (*x)->tag = Immediate_int;
    break;
  case 3:
    if (l != 1)
      return false;
    if (!Float_des(in, &(*x)->float32.f))
      return false;
    (*x)->tag = Immediate_float;
    break;
  default:
    return false;
  }
  return true;
}

bool ActivationImm_des(FILE *in, Ptr<ActivationImm> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 132)
    return false;
  *x = static_cast<ActivationImm *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Nat_des(in, &(*x)->reg.reg))
      return false;
    (*x)->tag = ActivationImm_register;
    break;
  case 1:
    if (l != 0)
      return false;
    (*x)->tag = ActivationImm_pointer;
    break;
  case 2:
    if (l != 1)
      return false;
    if (!Float_des(in, &(*x)->float32.f))
      return false;
    (*x)->tag = ActivationImm_float;
    break;
  default:
    return false;
  }
  return true;
}

bool DataPattern_des(FILE *in, Ptr<DataPattern> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 133 || c != 0 || l != 2)
    return false;
  *x = static_cast<DataPattern *>(region_alloc(region, sizeof(**x)));
  if (!Nat_des(in, &(*x)->offset))
    return false;
  if (!List_des(in, &(*x)->pattern))
    return false;
  return true;
}

bool AluOp_des(FILE *in, AluOp &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 134)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = AluOp::abs;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = AluOp::add;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = AluOp::arith_shift_left;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = AluOp::arith_shift_right;
    break;
  case 4:
    if (l != 0)
      return false;
    *x = AluOp::average;
    break;
  case 5:
    if (l != 0)
      return false;
    *x = AluOp::bitwise_and;
    break;
  case 6:
    if (l != 0)
      return false;
    *x = AluOp::bitwise_not;
    break;
  case 7:
    if (l != 0)
      return false;
    *x = AluOp::bitwise_or;
    break;
  case 8:
    if (l != 0)
      return false;
    *x = AluOp::bitwise_xor;
    break;
  case 9:
    if (l != 0)
      return false;
    *x = AluOp::bypass;
    break;
  case 10:
    if (l != 0)
      return false;
    *x = AluOp::divide;
    break;
  case 11:
    if (l != 0)
      return false;
    *x = AluOp::is_equal;
    break;
  case 12:
    if (l != 0)
      return false;
    *x = AluOp::is_ge;
    break;
  case 13:
    if (l != 0)
      return false;
    *x = AluOp::is_gt;
    break;
  case 14:
    if (l != 0)
      return false;
    *x = AluOp::is_le;
    break;
  case 15:
    if (l != 0)
      return false;
    *x = AluOp::is_lt;
    break;
  case 16:
    if (l != 0)
      return false;
    *x = AluOp::logical_and;
    break;
  case 17:
    if (l != 0)
      return false;
    *x = AluOp::logical_or;
    break;
  case 18:
    if (l != 0)
      return false;
    *x = AluOp::logical_shift_left;
    break;
  case 19:
    if (l != 0)
      return false;
    *x = AluOp::logical_shift_right;
    break;
  case 20:
    if (l != 0)
      return false;
    *x = AluOp::logical_xor;
    break;
  case 21:
    if (l != 0)
      return false;
    *x = AluOp::max;
    break;
  case 22:
    if (l != 0)
      return false;
    *x = AluOp::min;
    break;
  case 23:
    if (l != 0)
      return false;
    *x = AluOp::mod;
    break;
  case 24:
    if (l != 0)
      return false;
    *x = AluOp::mult;
    break;
  case 25:
    if (l != 0)
      return false;
    *x = AluOp::not_equal;
    break;
  case 26:
    if (l != 0)
      return false;
    *x = AluOp::pow;
    break;
  case 27:
    if (l != 0)
      return false;
    *x = AluOp::rsqrt;
    break;
  case 28:
    if (l != 0)
      return false;
    *x = AluOp::subtract;
    break;
  default:
    return false;
  }
  return true;
}

bool DropoutThresholdType_des(FILE *in, DropoutThresholdType &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 135)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = DropRate;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = KeepRate;
    break;
  default:
    return false;
  }
  return true;
}

bool AccumCmd_des(FILE *in, AccumCmd &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 136)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = Idle;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = Zero;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = Accumulate;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = ZeroAccumulate;
    break;
  case 4:
    if (l != 0)
      return false;
    *x = LoadAccumulate;
    break;
  default:
    return false;
  }
  return true;
}

bool ActivationFunc_des(FILE *in, ActivationFunc &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 137)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = ActivationFunc::abs;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = ActivationFunc::arctan;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = ActivationFunc::copy;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = ActivationFunc::erf;
    break;
  case 4:
    if (l != 0)
      return false;
    *x = ActivationFunc::erf_dx;
    break;
  case 5:
    if (l != 0)
      return false;
    *x = ActivationFunc::exp;
    break;
  case 6:
    if (l != 0)
      return false;
    *x = ActivationFunc::gelu;
    break;
  case 7:
    if (l != 0)
      return false;
    *x = ActivationFunc::gelu_apprx_tanh;
    break;
  case 8:
    if (l != 0)
      return false;
    *x = ActivationFunc::gelu_dx;
    break;
  case 9:
    if (l != 0)
      return false;
    *x = ActivationFunc::log;
    break;
  case 10:
    if (l != 0)
      return false;
    *x = ActivationFunc::mish;
    break;
  case 11:
    if (l != 0)
      return false;
    *x = ActivationFunc::reciprocal;
    break;
  case 12:
    if (l != 0)
      return false;
    *x = ActivationFunc::relu;
    break;
  case 13:
    if (l != 0)
      return false;
    *x = ActivationFunc::rsqrt;
    break;
  case 14:
    if (l != 0)
      return false;
    *x = ActivationFunc::sigmoid;
    break;
  case 15:
    if (l != 0)
      return false;
    *x = ActivationFunc::sign;
    break;
  case 16:
    if (l != 0)
      return false;
    *x = ActivationFunc::silu;
    break;
  case 17:
    if (l != 0)
      return false;
    *x = ActivationFunc::silu_dx;
    break;
  case 18:
    if (l != 0)
      return false;
    *x = ActivationFunc::sin;
    break;
  case 19:
    if (l != 0)
      return false;
    *x = ActivationFunc::softplus;
    break;
  case 20:
    if (l != 0)
      return false;
    *x = ActivationFunc::sqrt;
    break;
  case 21:
    if (l != 0)
      return false;
    *x = ActivationFunc::square;
    break;
  case 22:
    if (l != 0)
      return false;
    *x = ActivationFunc::tanh;
    break;
  default:
    return false;
  }
  return true;
}

bool AffineSelectCmp_des(FILE *in, AffineSelectCmp &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 138)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = GreaterThan;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = GreaterThanEq;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = Eq;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = NotEq;
    break;
  default:
    return false;
  }
  return true;
}

bool DgeComputeOp_des(FILE *in, DgeComputeOp &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 139)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = DgeComputeOp::none;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = DgeComputeOp::add;
    break;
  default:
    return false;
  }
  return true;
}

bool DmaBounds_des(FILE *in, Ptr<DmaBounds> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 140)
    return false;
  *x = static_cast<DmaBounds *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    (*x)->tag = DmaBounds_disable;
    break;
  case 1:
    if (l != 0)
      return false;
    (*x)->tag = DmaBounds_enable;
    break;
  case 2:
    if (l != 1)
      return false;
    if (!Nat_des(in, &(*x)->reg.reg))
      return false;
    (*x)->tag = DmaBounds_reg;
    break;
  default:
    return false;
  }
  return true;
}

bool MatmulGroupElement_des(FILE *in, MatmulGroupElement &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 141)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = MatmulGroupElement::first;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = MatmulGroupElement::middle;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = MatmulGroupElement::last;
    break;
  default:
    return false;
  }
  return true;
}

bool IndexMissBehavior_des(FILE *in, Ptr<IndexMissBehavior> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 142)
    return false;
  *x = static_cast<IndexMissBehavior *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Immediate_des(in, &(*x)->imm.value))
      return false;
    (*x)->tag = IndexMissBehavior_imm;
    break;
  case 1:
    if (l != 0)
      return false;
    (*x)->tag = IndexMissBehavior_skip;
    break;
  default:
    return false;
  }
  return true;
}

bool TensorScalarReverseOps_des(FILE *in, TensorScalarReverseOps &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 143)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = TensorScalarReverseOps::none;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = TensorScalarReverseOps::first;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = TensorScalarReverseOps::second;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = TensorScalarReverseOps::both;
    break;
  default:
    return false;
  }
  return true;
}

bool TensorSubDim_des(FILE *in, TensorSubDim &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 144)
    return false;
  (void)region;
  switch (c) {
  case 0:
    if (l != 0)
      return false;
    *x = X;
    break;
  case 1:
    if (l != 0)
      return false;
    *x = XY;
    break;
  case 2:
    if (l != 0)
      return false;
    *x = XYZ;
    break;
  case 3:
    if (l != 0)
      return false;
    *x = XYZW;
    break;
  default:
    return false;
  }
  return true;
}

bool Dropout_des(FILE *in, Ptr<Dropout> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 145 || c != 0 || l != 4)
    return false;
  *x = static_cast<Dropout *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!DropoutThresholdType_des(in, &(*x)->thresholdType))
    return false;
  if (!Immediate_des(in, &(*x)->threshold))
    return false;
  return true;
}

bool Activate_des(FILE *in, Ptr<Activate> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 146 || c != 0 || l != 7)
    return false;
  *x = static_cast<Activate *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!AccumCmd_des(in, &(*x)->accumulatorCmd))
    return false;
  if (!ActivationFunc_des(in, &(*x)->activationFunc))
    return false;
  if (!Immediate_des(in, &(*x)->scale))
    return false;
  if (!Immediate_des(in, &(*x)->bias))
    return false;
  if (!Immediate_des(in, &(*x)->imm))
    return false;
  return true;
}

bool AffineSelect_des(FILE *in, Ptr<AffineSelect> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 147 || c != 0 || l != 5)
    return false;
  *x = static_cast<AffineSelect *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!AffineSelectCmp_des(in, &(*x)->fillMode))
    return false;
  if (!Nat_des(in, &(*x)->fillReg))
    return false;
  if (!DataPattern_des(in, &(*x)->maskPattern))
    return false;
  return true;
}

bool DmaCopy_des(FILE *in, Ptr<DmaCopy> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 148 || c != 0 || l != 5)
    return false;
  *x = static_cast<DmaCopy *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!DgeComputeOp_des(in, &(*x)->compute_op))
    return false;
  if (!DmaBounds_des(in, &(*x)->dstBoundsCheck))
    return false;
  if (!DmaBounds_des(in, &(*x)->srcBoundsCheck))
    return false;
  return true;
}

bool DmaTranspose_des(FILE *in, Ptr<DmaTranspose> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 149 || c != 0 || l != 2)
    return false;
  *x = static_cast<DmaTranspose *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool Transpose_des(FILE *in, Ptr<Transpose> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 150 || c != 0 || l != 2)
    return false;
  *x = static_cast<Transpose *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool LoadMaskRegister_des(FILE *in, Ptr<LoadMaskRegister> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 151 || c != 0 || l != 1)
    return false;
  *x = static_cast<LoadMaskRegister *>(region_alloc(region, sizeof(**x)));
  if (!Nat_des(in, &(*x)->regNum))
    return false;
  return true;
}

bool Shuffle_des(FILE *in, Ptr<Shuffle> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 152 || c != 0 || l != 2)
    return false;
  *x = static_cast<Shuffle *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool MemSet_des(FILE *in, Ptr<MemSet> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 153 || c != 0 || l != 3)
    return false;
  *x = static_cast<MemSet *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!Nat_des(in, &(*x)->value))
    return false;
  if (!Nat_des(in, &(*x)->count))
    return false;
  return true;
}

bool Iota_des(FILE *in, Ptr<Iota> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 154 || c != 0 || l != 2)
    return false;
  *x = static_cast<Iota *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!DataPattern_des(in, &(*x)->pattern))
    return false;
  return true;
}

bool LoadStationary_des(FILE *in, Ptr<LoadStationary> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 155 || c != 0 || l != 2)
    return false;
  *x = static_cast<LoadStationary *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!Bool_des(in, &(*x)->isTranspose))
    return false;
  return true;
}

bool MatMul_des(FILE *in, Ptr<MatMul> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 156 || c != 0 || l != 3)
    return false;
  *x = static_cast<MatMul *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->moving))
    return false;
  if (!MatmulGroupElement_des(in, &(*x)->psumAccumulateFlag))
    return false;
  return true;
}

bool LocalGather_des(FILE *in, Ptr<LocalGather> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 157 || c != 0 || l != 4)
    return false;
  *x = static_cast<LocalGather *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!IndexMissBehavior_des(in, &(*x)->indexMissBehavior))
    return false;
  if (!Bool_des(in, &(*x)->freePoolBuffer))
    return false;
  return true;
}

bool RangeSelect_des(FILE *in, Ptr<RangeSelect> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 158 || c != 0 || l != 10)
    return false;
  *x = static_cast<RangeSelect *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!AccumCmd_des(in, &(*x)->reduceCommand))
    return false;
  if (!AluOp_des(in, &(*x)->reduceOp))
    return false;
  if (!Float_des(in, &(*x)->base))
    return false;
  if (!Float_des(in, &(*x)->fillValue))
    return false;
  if (!AluOp_des(in, &(*x)->compOp0))
    return false;
  if (!AluOp_des(in, &(*x)->compOp1))
    return false;
  if (!Immediate_des(in, &(*x)->bound0))
    return false;
  if (!Immediate_des(in, &(*x)->bound1))
    return false;
  return true;
}

bool ScalarTensorTensor_des(FILE *in, Ptr<ScalarTensorTensor> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 159 || c != 0 || l != 8)
    return false;
  *x = static_cast<ScalarTensorTensor *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src0))
    return false;
  if (!TensorRef_des(in, &(*x)->src1))
    return false;
  if (!AluOp_des(in, &(*x)->op0))
    return false;
  if (!AluOp_des(in, &(*x)->op1))
    return false;
  if (!TensorScalarReverseOps_des(in, &(*x)->reverseOperands))
    return false;
  if (!Immediate_des(in, &(*x)->imm0))
    return false;
  if (!AccumCmd_des(in, &(*x)->accumulatorCmd))
    return false;
  return true;
}

bool CopyPredicated_des(FILE *in, Ptr<CopyPredicated> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 160 || c != 0 || l != 3)
    return false;
  *x = static_cast<CopyPredicated *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!TensorRef_des(in, &(*x)->predicate))
    return false;
  return true;
}

bool TensorTensorScan_des(FILE *in, Ptr<TensorTensorScan> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 161 || c != 0 || l != 8)
    return false;
  *x = static_cast<TensorTensorScan *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src0))
    return false;
  if (!TensorRef_des(in, &(*x)->src1))
    return false;
  if (!AluOp_des(in, &(*x)->op0))
    return false;
  if (!AluOp_des(in, &(*x)->op1))
    return false;
  if (!TensorScalarReverseOps_des(in, &(*x)->reverseOperands))
    return false;
  if (!Immediate_des(in, &(*x)->imm0))
    return false;
  if (!AccumCmd_des(in, &(*x)->accumulatorCmd))
    return false;
  return true;
}

bool MatchValueLoad_des(FILE *in, Ptr<MatchValueLoad> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 162 || c != 0 || l != 1)
    return false;
  *x = static_cast<MatchValueLoad *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool FindIndex8_des(FILE *in, Ptr<FindIndex8> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 163 || c != 0 || l != 2)
    return false;
  *x = static_cast<FindIndex8 *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool MatchReplace8_des(FILE *in, Ptr<MatchReplace8> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 164 || c != 0 || l != 3)
    return false;
  *x = static_cast<MatchReplace8 *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!Float_des(in, &(*x)->replaceValue))
    return false;
  return true;
}

bool Max8_des(FILE *in, Ptr<Max8> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 165 || c != 0 || l != 2)
    return false;
  *x = static_cast<Max8 *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool BatchNormAggregate_des(FILE *in, Ptr<BatchNormAggregate> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 166 || c != 0 || l != 2)
    return false;
  *x = static_cast<BatchNormAggregate *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool BatchNormStats_des(FILE *in, Ptr<BatchNormStats> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 167 || c != 0 || l != 2)
    return false;
  *x = static_cast<BatchNormStats *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool Reciprocal_des(FILE *in, Ptr<Reciprocal> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 168 || c != 0 || l != 2)
    return false;
  *x = static_cast<Reciprocal *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  return true;
}

bool Copy_des(FILE *in, Ptr<Copy> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 169 || c != 0 || l != 3)
    return false;
  *x = static_cast<Copy *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!Option_des(in, &(*x)->opDim))
    return false;
  return true;
}

bool TensorReduce_des(FILE *in, Ptr<TensorReduce> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 170 || c != 0 || l != 5)
    return false;
  *x = static_cast<TensorReduce *>(region_alloc(region, sizeof(**x)));
  if (!TensorRef_des(in, &(*x)->dst))
    return false;
  if (!TensorRef_des(in, &(*x)->src))
    return false;
  if (!AluOp_des(in, &(*x)->op))
    return false;
  if (!TensorSubDim_des(in, &(*x)->opDim))
    return false;
  if (!Bool_des(in, &(*x)->negated))
    return false;
  return true;
}

bool Operator_des(FILE *in, Ptr<Operator> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 171)
    return false;
  *x = static_cast<Operator *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Activate_des(in, &(*x)->activate.op))
      return false;
    (*x)->tag = Operator_activate;
    break;
  case 1:
    if (l != 1)
      return false;
    if (!AffineSelect_des(in, &(*x)->affineSelect.op))
      return false;
    (*x)->tag = Operator_affineSelect;
    break;
  case 2:
    if (l != 1)
      return false;
    if (!BatchNormAggregate_des(in, &(*x)->batchNormAggregate.op))
      return false;
    (*x)->tag = Operator_batchNormAggregate;
    break;
  case 3:
    if (l != 1)
      return false;
    if (!BatchNormStats_des(in, &(*x)->batchNormStats.op))
      return false;
    (*x)->tag = Operator_batchNormStats;
    break;
  case 4:
    if (l != 1)
      return false;
    if (!Copy_des(in, &(*x)->copy.op))
      return false;
    (*x)->tag = Operator_copy;
    break;
  case 5:
    if (l != 1)
      return false;
    if (!CopyPredicated_des(in, &(*x)->copyPredicated.op))
      return false;
    (*x)->tag = Operator_copyPredicated;
    break;
  case 6:
    if (l != 1)
      return false;
    if (!DmaCopy_des(in, &(*x)->dmaCopy.op))
      return false;
    (*x)->tag = Operator_dmaCopy;
    break;
  case 7:
    if (l != 1)
      return false;
    if (!DmaTranspose_des(in, &(*x)->dmaTranspose.op))
      return false;
    (*x)->tag = Operator_dmaTranspose;
    break;
  case 8:
    if (l != 1)
      return false;
    if (!Dropout_des(in, &(*x)->dropout.op))
      return false;
    (*x)->tag = Operator_dropout;
    break;
  case 9:
    if (l != 1)
      return false;
    if (!FindIndex8_des(in, &(*x)->findIndex8.op))
      return false;
    (*x)->tag = Operator_findIndex8;
    break;
  case 10:
    if (l != 1)
      return false;
    if (!Iota_des(in, &(*x)->iota.op))
      return false;
    (*x)->tag = Operator_iota;
    break;
  case 11:
    if (l != 1)
      return false;
    if (!LoadMaskRegister_des(in, &(*x)->loadMaskRegister.op))
      return false;
    (*x)->tag = Operator_loadMaskRegister;
    break;
  case 12:
    if (l != 1)
      return false;
    if (!LoadStationary_des(in, &(*x)->loadStationary.op))
      return false;
    (*x)->tag = Operator_loadStationary;
    break;
  case 13:
    if (l != 1)
      return false;
    if (!LocalGather_des(in, &(*x)->localGather.op))
      return false;
    (*x)->tag = Operator_localGather;
    break;
  case 14:
    if (l != 1)
      return false;
    if (!MatMul_des(in, &(*x)->matMul.op))
      return false;
    (*x)->tag = Operator_matMul;
    break;
  case 15:
    if (l != 1)
      return false;
    if (!MatchReplace8_des(in, &(*x)->matchReplace8.op))
      return false;
    (*x)->tag = Operator_matchReplace8;
    break;
  case 16:
    if (l != 1)
      return false;
    if (!MatchValueLoad_des(in, &(*x)->matchValueLoad.op))
      return false;
    (*x)->tag = Operator_matchValueLoad;
    break;
  case 17:
    if (l != 1)
      return false;
    if (!Max8_des(in, &(*x)->max8.op))
      return false;
    (*x)->tag = Operator_max8;
    break;
  case 18:
    if (l != 1)
      return false;
    if (!MemSet_des(in, &(*x)->memSet.op))
      return false;
    (*x)->tag = Operator_memSet;
    break;
  case 19:
    if (l != 1)
      return false;
    if (!RangeSelect_des(in, &(*x)->rangeSelect.op))
      return false;
    (*x)->tag = Operator_rangeSelect;
    break;
  case 20:
    if (l != 1)
      return false;
    if (!Reciprocal_des(in, &(*x)->reciprocal.op))
      return false;
    (*x)->tag = Operator_reciprocal;
    break;
  case 21:
    if (l != 1)
      return false;
    if (!ScalarTensorTensor_des(in, &(*x)->scalarTensorTensor.op))
      return false;
    (*x)->tag = Operator_scalarTensorTensor;
    break;
  case 22:
    if (l != 1)
      return false;
    if (!Shuffle_des(in, &(*x)->shuffle.op))
      return false;
    (*x)->tag = Operator_shuffle;
    break;
  case 23:
    if (l != 1)
      return false;
    if (!TensorReduce_des(in, &(*x)->tensorReduce.op))
      return false;
    (*x)->tag = Operator_tensorReduce;
    break;
  case 24:
    if (l != 1)
      return false;
    if (!TensorTensorScan_des(in, &(*x)->tensorTensorScan.op))
      return false;
    (*x)->tag = Operator_tensorTensorScan;
    break;
  case 25:
    if (l != 1)
      return false;
    if (!Transpose_des(in, &(*x)->transpose.op))
      return false;
    (*x)->tag = Operator_transpose;
    break;
  default:
    return false;
  }
  return true;
}

bool Value_des(FILE *in, Ptr<Value> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 101)
    return false;
  *x = static_cast<Value *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!String_des(in, &(*x)->var.x))
      return false;
    (*x)->tag = Value_var;
    break;
  case 1:
    if (l != 1)
      return false;
    if (!Bool_des(in, &(*x)->boolean.value))
      return false;
    (*x)->tag = Value_bool;
    break;
  case 2:
    if (l != 1)
      return false;
    if (!Int_des(in, &(*x)->int32.value))
      return false;
    (*x)->tag = Value_int;
    break;
  case 3:
    if (l != 1)
      return false;
    if (!Float_des(in, &(*x)->float32.value))
      return false;
    (*x)->tag = Value_float;
    break;
  case 4:
    if (l != 1)
      return false;
    if (!Access_des(in, &(*x)->access.a))
      return false;
    (*x)->tag = Value_access;
    break;
  default:
    return false;
  }
  return true;
}

bool Keyword_des(FILE *in, Ptr<Keyword> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 102 || c != 0 || l != 2)
    return false;
  *x = static_cast<Keyword *>(region_alloc(region, sizeof(**x)));
  if (!String_des(in, &(*x)->name))
    return false;
  if (!Value_des(in, &(*x)->value))
    return false;
  return true;
}

bool Expr_des(FILE *in, Ptr<Expr> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 103)
    return false;
  *x = static_cast<Expr *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Value_des(in, &(*x)->value.v))
      return false;
    (*x)->tag = Expr_value;
    break;
  case 1:
    if (l != 3)
      return false;
    if (!String_des(in, &(*x)->call.f))
      return false;
    if (!List_des(in, &(*x)->call.args))
      return false;
    if (!List_des(in, &(*x)->call.kwargs))
      return false;
    (*x)->tag = Expr_call;
    break;
  default:
    return false;
  }
  return true;
}

bool Stmt_des(FILE *in, Ptr<Stmt> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 104)
    return false;
  *x = static_cast<Stmt *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Value_des(in, &(*x)->ret.v))
      return false;
    (*x)->tag = Stmt_ret;
    break;
  case 1:
    if (l != 2)
      return false;
    if (!String_des(in, &(*x)->assign.x))
      return false;
    if (!Expr_des(in, &(*x)->assign.e))
      return false;
    (*x)->tag = Stmt_assign;
    break;
  case 2:
    if (l != 3)
      return false;
    if (!Access_des(in, &(*x)->store.dst))
      return false;
    if (!Operator_des(in, &(*x)->store.op))
      return false;
    if (!List_des(in, &(*x)->store.args))
      return false;
    (*x)->tag = Stmt_store;
    break;
  default:
    return false;
  }
  return true;
}

bool Kernel_des(FILE *in, Ptr<Kernel> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 105 || c != 0 || l != 4)
    return false;
  *x = static_cast<Kernel *>(region_alloc(region, sizeof(**x)));
  if (!String_des(in, &(*x)->name))
    return false;
  if (!List_des(in, &(*x)->inputs))
    return false;
  if (!List_des(in, &(*x)->outputs))
    return false;
  if (!List_des(in, &(*x)->body))
    return false;
  return true;
}

bool List_des(FILE *in, List<Ptr<Index>> &x) { return true; }

bool List_des(FILE *in, List<Ptr<APPair>> &x) { return true; }

bool Option_des(FILE *in, Option<TensorSubDim> &x) { return true; }

bool List_des(FILE *in, List<Ptr<Value>> &x) { return true; }

bool List_des(FILE *in, List<Ptr<Keyword>> &x) { return true; }

bool List_des(FILE *in, List<Ptr<TensorArg>> &x) { return true; }

bool List_des(FILE *in, List<Ptr<Stmt>> &x) { return true; }

bool KLRFile_des(FILE *in, Ptr<KLRFile> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 217 || c != 247 || l != 3)
    return false;
  *x = static_cast<KLRFile *>(region_alloc(region, sizeof(**x)));
  if (!Nat_des(in, &(*x)->major))
    return false;
  if (!Nat_des(in, &(*x)->minor))
    return false;
  if (!Nat_des(in, &(*x)->patch))
    return false;
  return true;
}

bool KLRMetaData_des(FILE *in, Ptr<KLRMetaData> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 235 || c != 0 || l != 1)
    return false;
  *x = static_cast<KLRMetaData *>(region_alloc(region, sizeof(**x)));
  if (!String_des(in, &(*x)->format))
    return false;
  return true;
}

bool Contents_des(FILE *in, Ptr<Contents> &x) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    return false;
  if (t != 236)
    return false;
  *x = static_cast<Contents *>(region_alloc(region, sizeof(**x)));
  switch (c) {
  case 0:
    if (l != 1)
      return false;
    if (!Kernel_des(in, &(*x)->python.kernel))
      return false;
    (*x)->tag = Contents_python;
    break;
  case 1:
    if (l != 1)
      return false;
    if (!Kernel_des(in, &(*x)->nki.kernel))
      return false;
    (*x)->tag = Contents_nki;
    break;
  case 2:
    if (l != 1)
      return false;
    if (!Kernel_des(in, &(*x)->klir.kernel))
      return false;
    (*x)->tag = Contents_klir;
    break;
  case 3:
    if (l != 1)
      return false;
    if (!String_des(in, &(*x)->hlo.name))
      return false;
    (*x)->tag = Contents_hlo;
    break;
  default:
    return false;
  }
  return true;
}
