/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Written by the KLR Contributors (https://github.com/leanprover/KLR)
*/

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "klir_common.hpp"
#include "klir_serde.hpp"

namespace klr {

List<Bool> List_Bool_des(FILE *in) {
  List<Bool> x;
  return x;
}

List<Nat> List_Nat_des(FILE *in) {
  List<Nat> x;
  return x;
}

List<Int> List_Int_des(FILE *in) {
  List<Int> x;
  return x;
}

List<Float> List_Float_des(FILE *in) {
  List<Float> x;
  return x;
}

List<String> List_String_des(FILE *in) {
  List<String> x;
  return x;
}

Option<Bool> Option_Bool_des(FILE *in) {
  Option<Bool> x;
  return x;
}

Option<Nat> Option_Nat_des(FILE *in) {
  Option<Nat> x;
  return x;
}

Option<Int> Option_Int_des(FILE *in) {
  Option<Int> x;
  return x;
}

Option<Float> Option_Float_des(FILE *in) {
  Option<Float> x;
  return x;
}

Option<String> Option_String_des(FILE *in) {
  Option<String> x;
  return x;
}

Ptr<Pos> Pos_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 100 || c != 0 || l != 4)
    throw std::runtime_error("rror");
  Ptr<Pos> x = ptr<Pos>();
  x->line = Nat_des(in);
  x->column = Nat_des(in);
  x->lineEnd = Option_Nat_des(in);
  x->columnEnd = Option_Nat_des(in);
  return x;
}

Memory Memory_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 110)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Memory::hbm;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Memory::sbuf;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Memory::pmem;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Memory::reg;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Dtype Dtype_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 111)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::bfloat16;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::float8e3;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::float8e4;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::float8e5;
    break;
  }
  case 4: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::float16;
    break;
  }
  case 5: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::float32;
    break;
  }
  case 6: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::float32r;
    break;
  }
  case 7: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::int8;
    break;
  }
  case 8: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::int16;
    break;
  }
  case 9: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::int64;
    break;
  }
  case 10: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::int32;
    break;
  }
  case 11: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::uint8;
    break;
  }
  case 12: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::uint16;
    break;
  }
  case 13: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::uint32;
    break;
  }
  case 14: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Dtype::uint64;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<Shape> Shape_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 112 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<Shape> x = ptr<Shape>();
  x->parDim = Nat_des(in);
  x->freeDims = List_Nat_des(in);
  return x;
}

Ptr<Address> Address_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 113 || c != 0 || l != 5)
    throw std::runtime_error("rror");
  Ptr<Address> x = ptr<Address>();
  x->memory = Memory_des(in);
  x->parSize = Nat_des(in);
  x->freeSize = Nat_des(in);
  x->parOffset = Option_Nat_des(in);
  x->freeOffset = Option_Nat_des(in);
  return x;
}

Ptr<TensorSram> TensorSram_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 114 || c != 0 || l != 6)
    throw std::runtime_error("rror");
  Ptr<TensorSram> x = ptr<TensorSram>();
  x->name = String_des(in);
  x->dtype = Dtype_des(in);
  x->shape = Shape_des(in);
  x->address = Address_des(in);
  x->parWF = Prop_des(in);
  x->freeWF = Prop_des(in);
  return x;
}

Ptr<Slice> Slice_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 115 || c != 0 || l != 4)
    throw std::runtime_error("rror");
  Ptr<Slice> x = ptr<Slice>();
  x->l = Nat_des(in);
  x->u = Nat_des(in);
  x->step = Int_des(in);
  x->wf = Prop_des(in);
  return x;
}

Ptr<Index> Index_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 116)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<IndexCoordWrapper> x = ptr<IndexCoordWrapper>();
    x->e = Nat_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<IndexSliceWrapper> x = ptr<IndexSliceWrapper>();
    x->slice = Slice_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<AccessBasic> AccessBasic_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 117 || c != 0 || l != 3)
    throw std::runtime_error("rror");
  Ptr<AccessBasic> x = ptr<AccessBasic>();
  x->tensor = TensorSram_des(in);
  x->indexes = List_Index_des(in);
  x->lenWF = Prop_des(in);
  return x;
}

Ptr<APPair> APPair_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 118 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<APPair> x = ptr<APPair>();
  x->step = Int_des(in);
  x->num = Nat_des(in);
  return x;
}

Ptr<AccessPattern> AccessPattern_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 119 || c != 0 || l != 4)
    throw std::runtime_error("rror");
  Ptr<AccessPattern> x = ptr<AccessPattern>();
  x->tensor = TensorSram_des(in);
  x->parNum = Nat_des(in);
  x->freePattern = List_APPair_des(in);
  x->offset = Nat_des(in);
  return x;
}

Ptr<Access> Access_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 120)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<AccessSimpleWrapper> x = ptr<AccessSimpleWrapper>();
    x->tensor = TensorSram_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<AccessBasicWrapper> x = ptr<AccessBasicWrapper>();
    x->access = AccessBasic_des(in);
    return x;
    break;
  }
  case 2: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<AccessPatternWrapper> x = ptr<AccessPatternWrapper>();
    x->access = AccessPattern_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<TensorHbm> TensorHbm_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 121 || c != 0 || l != 4)
    throw std::runtime_error("rror");
  Ptr<TensorHbm> x = ptr<TensorHbm>();
  x->dtype = Dtype_des(in);
  x->address = Nat_des(in);
  x->shape = List_Nat_des(in);
  x->strides = List_Nat_des(in);
  return x;
}

ParQuadrant ParQuadrant_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 122)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ParQuadrant::par0;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ParQuadrant::par32;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ParQuadrant::par64;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ParQuadrant::par96;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<TensorView> TensorView_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 123 || c != 0 || l != 6)
    throw std::runtime_error("rror");
  Ptr<TensorView> x = ptr<TensorView>();
  x->name = String_des(in);
  x->dtype = Dtype_des(in);
  x->parQuadrant = ParQuadrant_des(in);
  x->parDim = Nat_des(in);
  x->freeOffset = Nat_des(in);
  x->freePattern = List_APPair_des(in);
  return x;
}

Ptr<TensorRef> TensorRef_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 124)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<TensorRefAbstractWrapper> x = ptr<TensorRefAbstractWrapper>();
    x->access = Access_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<TensorRefLiteralWrapper> x = ptr<TensorRefLiteralWrapper>();
    x->view = TensorView_des(in);
    return x;
    break;
  }
  case 2: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<TensorRefRegisterWrapper> x = ptr<TensorRefRegisterWrapper>();
    x->reg = Nat_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<TensorArg> TensorArg_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 125)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<TensorArgHbmWrapper> x = ptr<TensorArgHbmWrapper>();
    x->tensor = TensorHbm_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<TensorArgSramWrapper> x = ptr<TensorArgSramWrapper>();
    x->tensor = TensorSram_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Engine Engine_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 130)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Engine::unassigned;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Engine::act;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Engine::dma;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Engine::dve;
    break;
  }
  case 4: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Engine::pe;
    break;
  }
  case 5: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Engine::pool;
    break;
  }
  case 6: {
    if (l != 0)
      throw std::runtime_error("rror");
    return Engine::sp;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<Immediate> Immediate_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 131)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ImmediateRegisterWrapper> x = ptr<ImmediateRegisterWrapper>();
    x->reg = Nat_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    Ptr<ImmediatePointerWrapper> x = ptr<ImmediatePointerWrapper>();
    return x;
    break;
  }
  case 2: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ImmediateIntWrapper> x = ptr<ImmediateIntWrapper>();
    x->i = Int_des(in);
    return x;
    break;
  }
  case 3: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ImmediateFloatWrapper> x = ptr<ImmediateFloatWrapper>();
    x->f = Float_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<ActivationImm> ActivationImm_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 132)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ActivationImmRegisterWrapper> x = ptr<ActivationImmRegisterWrapper>();
    x->reg = Nat_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    Ptr<ActivationImmPointerWrapper> x = ptr<ActivationImmPointerWrapper>();
    return x;
    break;
  }
  case 2: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ActivationImmFloatWrapper> x = ptr<ActivationImmFloatWrapper>();
    x->f = Float_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<DataPattern> DataPattern_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 133 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<DataPattern> x = ptr<DataPattern>();
  x->offset = Nat_des(in);
  x->pattern = List_APPair_des(in);
  return x;
}

AluOp AluOp_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 134)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::abs;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::add;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::arith_shift_left;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::arith_shift_right;
    break;
  }
  case 4: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::average;
    break;
  }
  case 5: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::bitwise_and;
    break;
  }
  case 6: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::bitwise_not;
    break;
  }
  case 7: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::bitwise_or;
    break;
  }
  case 8: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::bitwise_xor;
    break;
  }
  case 9: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::bypass;
    break;
  }
  case 10: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::divide;
    break;
  }
  case 11: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::is_equal;
    break;
  }
  case 12: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::is_ge;
    break;
  }
  case 13: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::is_gt;
    break;
  }
  case 14: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::is_le;
    break;
  }
  case 15: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::is_lt;
    break;
  }
  case 16: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::logical_and;
    break;
  }
  case 17: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::logical_or;
    break;
  }
  case 18: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::logical_shift_left;
    break;
  }
  case 19: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::logical_shift_right;
    break;
  }
  case 20: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::logical_xor;
    break;
  }
  case 21: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::max;
    break;
  }
  case 22: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::min;
    break;
  }
  case 23: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::mod;
    break;
  }
  case 24: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::mult;
    break;
  }
  case 25: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::not_equal;
    break;
  }
  case 26: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::pow;
    break;
  }
  case 27: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::rsqrt;
    break;
  }
  case 28: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AluOp::subtract;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

DropoutThresholdType DropoutThresholdType_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 135)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return DropoutThresholdType::DropRate;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return DropoutThresholdType::KeepRate;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

AccumCmd AccumCmd_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 136)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AccumCmd::Idle;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AccumCmd::Zero;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AccumCmd::Accumulate;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AccumCmd::ZeroAccumulate;
    break;
  }
  case 4: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AccumCmd::LoadAccumulate;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

ActivationFunc ActivationFunc_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 137)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::abs;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::arctan;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::copy;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::erf;
    break;
  }
  case 4: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::erf_dx;
    break;
  }
  case 5: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::exp;
    break;
  }
  case 6: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::gelu;
    break;
  }
  case 7: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::gelu_apprx_tanh;
    break;
  }
  case 8: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::gelu_dx;
    break;
  }
  case 9: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::log;
    break;
  }
  case 10: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::mish;
    break;
  }
  case 11: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::reciprocal;
    break;
  }
  case 12: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::relu;
    break;
  }
  case 13: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::rsqrt;
    break;
  }
  case 14: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::sigmoid;
    break;
  }
  case 15: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::sign;
    break;
  }
  case 16: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::silu;
    break;
  }
  case 17: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::silu_dx;
    break;
  }
  case 18: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::sin;
    break;
  }
  case 19: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::softplus;
    break;
  }
  case 20: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::sqrt;
    break;
  }
  case 21: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::square;
    break;
  }
  case 22: {
    if (l != 0)
      throw std::runtime_error("rror");
    return ActivationFunc::tanh;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

AffineSelectCmp AffineSelectCmp_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 138)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AffineSelectCmp::GreaterThan;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AffineSelectCmp::GreaterThanEq;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AffineSelectCmp::Eq;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return AffineSelectCmp::NotEq;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

DgeComputeOp DgeComputeOp_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 139)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return DgeComputeOp::none;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return DgeComputeOp::add;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<DmaBounds> DmaBounds_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 140)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    Ptr<DmaBoundsDisableWrapper> x = ptr<DmaBoundsDisableWrapper>();
    return x;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    Ptr<DmaBoundsEnableWrapper> x = ptr<DmaBoundsEnableWrapper>();
    return x;
    break;
  }
  case 2: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<DmaBoundsRegWrapper> x = ptr<DmaBoundsRegWrapper>();
    x->reg = Nat_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

MatmulGroupElement MatmulGroupElement_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 141)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return MatmulGroupElement::first;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return MatmulGroupElement::middle;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return MatmulGroupElement::last;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<IndexMissBehavior> IndexMissBehavior_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 142)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<IndexMissBehaviorImmWrapper> x = ptr<IndexMissBehaviorImmWrapper>();
    x->value = Immediate_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    Ptr<IndexMissBehaviorSkipWrapper> x = ptr<IndexMissBehaviorSkipWrapper>();
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

TensorScalarReverseOps TensorScalarReverseOps_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 143)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return TensorScalarReverseOps::none;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return TensorScalarReverseOps::first;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return TensorScalarReverseOps::second;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return TensorScalarReverseOps::both;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

TensorSubDim TensorSubDim_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 144)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 0)
      throw std::runtime_error("rror");
    return TensorSubDim::X;
    break;
  }
  case 1: {
    if (l != 0)
      throw std::runtime_error("rror");
    return TensorSubDim::XY;
    break;
  }
  case 2: {
    if (l != 0)
      throw std::runtime_error("rror");
    return TensorSubDim::XYZ;
    break;
  }
  case 3: {
    if (l != 0)
      throw std::runtime_error("rror");
    return TensorSubDim::XYZW;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<Dropout> Dropout_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 145 || c != 0 || l != 4)
    throw std::runtime_error("rror");
  Ptr<Dropout> x = ptr<Dropout>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->thresholdType = DropoutThresholdType_des(in);
  x->threshold = Immediate_des(in);
  return x;
}

Ptr<Activate> Activate_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 146 || c != 0 || l != 7)
    throw std::runtime_error("rror");
  Ptr<Activate> x = ptr<Activate>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->accumulatorCmd = AccumCmd_des(in);
  x->activationFunc = ActivationFunc_des(in);
  x->scale = Immediate_des(in);
  x->bias = Immediate_des(in);
  x->imm = Immediate_des(in);
  return x;
}

Ptr<AffineSelect> AffineSelect_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 147 || c != 0 || l != 5)
    throw std::runtime_error("rror");
  Ptr<AffineSelect> x = ptr<AffineSelect>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->fillMode = AffineSelectCmp_des(in);
  x->fillReg = Nat_des(in);
  x->maskPattern = DataPattern_des(in);
  return x;
}

Ptr<DmaCopy> DmaCopy_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 148 || c != 0 || l != 5)
    throw std::runtime_error("rror");
  Ptr<DmaCopy> x = ptr<DmaCopy>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->compute_op = DgeComputeOp_des(in);
  x->dstBoundsCheck = DmaBounds_des(in);
  x->srcBoundsCheck = DmaBounds_des(in);
  return x;
}

Ptr<DmaTranspose> DmaTranspose_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 149 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<DmaTranspose> x = ptr<DmaTranspose>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  return x;
}

Ptr<Transpose> Transpose_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 150 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<Transpose> x = ptr<Transpose>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  return x;
}

Ptr<LoadMaskRegister> LoadMaskRegister_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 151 || c != 0 || l != 1)
    throw std::runtime_error("rror");
  Ptr<LoadMaskRegister> x = ptr<LoadMaskRegister>();
  x->regNum = Nat_des(in);
  return x;
}

Ptr<Shuffle> Shuffle_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 152 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<Shuffle> x = ptr<Shuffle>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  return x;
}

Ptr<MemSet> MemSet_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 153 || c != 0 || l != 3)
    throw std::runtime_error("rror");
  Ptr<MemSet> x = ptr<MemSet>();
  x->dst = TensorRef_des(in);
  x->value = Nat_des(in);
  x->count = Nat_des(in);
  return x;
}

Ptr<Iota> Iota_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 154 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<Iota> x = ptr<Iota>();
  x->dst = TensorRef_des(in);
  x->pattern = DataPattern_des(in);
  return x;
}

Ptr<LoadStationary> LoadStationary_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 155 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<LoadStationary> x = ptr<LoadStationary>();
  x->src = TensorRef_des(in);
  x->isTranspose = Bool_des(in);
  return x;
}

Ptr<MatMul> MatMul_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 156 || c != 0 || l != 3)
    throw std::runtime_error("rror");
  Ptr<MatMul> x = ptr<MatMul>();
  x->dst = TensorRef_des(in);
  x->moving = TensorRef_des(in);
  x->psumAccumulateFlag = MatmulGroupElement_des(in);
  return x;
}

Ptr<LocalGather> LocalGather_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 157 || c != 0 || l != 4)
    throw std::runtime_error("rror");
  Ptr<LocalGather> x = ptr<LocalGather>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->indexMissBehavior = IndexMissBehavior_des(in);
  x->freePoolBuffer = Bool_des(in);
  return x;
}

Ptr<RangeSelect> RangeSelect_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 158 || c != 0 || l != 10)
    throw std::runtime_error("rror");
  Ptr<RangeSelect> x = ptr<RangeSelect>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->reduceCommand = AccumCmd_des(in);
  x->reduceOp = AluOp_des(in);
  x->base = Float_des(in);
  x->fillValue = Float_des(in);
  x->compOp0 = AluOp_des(in);
  x->compOp1 = AluOp_des(in);
  x->bound0 = Immediate_des(in);
  x->bound1 = Immediate_des(in);
  return x;
}

Ptr<ScalarTensorTensor> ScalarTensorTensor_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 159 || c != 0 || l != 8)
    throw std::runtime_error("rror");
  Ptr<ScalarTensorTensor> x = ptr<ScalarTensorTensor>();
  x->dst = TensorRef_des(in);
  x->src0 = TensorRef_des(in);
  x->src1 = TensorRef_des(in);
  x->op0 = AluOp_des(in);
  x->op1 = AluOp_des(in);
  x->reverseOperands = TensorScalarReverseOps_des(in);
  x->imm0 = Immediate_des(in);
  x->accumulatorCmd = AccumCmd_des(in);
  return x;
}

Ptr<CopyPredicated> CopyPredicated_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 160 || c != 0 || l != 3)
    throw std::runtime_error("rror");
  Ptr<CopyPredicated> x = ptr<CopyPredicated>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->predicate = TensorRef_des(in);
  return x;
}

Ptr<TensorTensorScan> TensorTensorScan_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 161 || c != 0 || l != 8)
    throw std::runtime_error("rror");
  Ptr<TensorTensorScan> x = ptr<TensorTensorScan>();
  x->dst = TensorRef_des(in);
  x->src0 = TensorRef_des(in);
  x->src1 = TensorRef_des(in);
  x->op0 = AluOp_des(in);
  x->op1 = AluOp_des(in);
  x->reverseOperands = TensorScalarReverseOps_des(in);
  x->imm0 = Immediate_des(in);
  x->accumulatorCmd = AccumCmd_des(in);
  return x;
}

Ptr<MatchValueLoad> MatchValueLoad_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 162 || c != 0 || l != 1)
    throw std::runtime_error("rror");
  Ptr<MatchValueLoad> x = ptr<MatchValueLoad>();
  x->src = TensorRef_des(in);
  return x;
}

Ptr<FindIndex8> FindIndex8_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 163 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<FindIndex8> x = ptr<FindIndex8>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  return x;
}

Ptr<MatchReplace8> MatchReplace8_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 164 || c != 0 || l != 3)
    throw std::runtime_error("rror");
  Ptr<MatchReplace8> x = ptr<MatchReplace8>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->replaceValue = Float_des(in);
  return x;
}

Ptr<Max8> Max8_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 165 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<Max8> x = ptr<Max8>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  return x;
}

Ptr<BatchNormAggregate> BatchNormAggregate_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 166 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<BatchNormAggregate> x = ptr<BatchNormAggregate>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  return x;
}

Ptr<BatchNormStats> BatchNormStats_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 167 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<BatchNormStats> x = ptr<BatchNormStats>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  return x;
}

Ptr<Reciprocal> Reciprocal_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 168 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<Reciprocal> x = ptr<Reciprocal>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  return x;
}

Ptr<Copy> Copy_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 169 || c != 0 || l != 3)
    throw std::runtime_error("rror");
  Ptr<Copy> x = ptr<Copy>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->opDim = Option_TensorSubDim_des(in);
  return x;
}

Ptr<TensorReduce> TensorReduce_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 170 || c != 0 || l != 5)
    throw std::runtime_error("rror");
  Ptr<TensorReduce> x = ptr<TensorReduce>();
  x->dst = TensorRef_des(in);
  x->src = TensorRef_des(in);
  x->op = AluOp_des(in);
  x->opDim = TensorSubDim_des(in);
  x->negated = Bool_des(in);
  return x;
}

Ptr<Operator> Operator_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 171)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorActivateWrapper> x = ptr<OperatorActivateWrapper>();
    x->op = Activate_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorAffineSelectWrapper> x = ptr<OperatorAffineSelectWrapper>();
    x->op = AffineSelect_des(in);
    return x;
    break;
  }
  case 2: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorBatchNormAggregateWrapper> x =
        ptr<OperatorBatchNormAggregateWrapper>();
    x->op = BatchNormAggregate_des(in);
    return x;
    break;
  }
  case 3: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorBatchNormStatsWrapper> x = ptr<OperatorBatchNormStatsWrapper>();
    x->op = BatchNormStats_des(in);
    return x;
    break;
  }
  case 4: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorCopyWrapper> x = ptr<OperatorCopyWrapper>();
    x->op = Copy_des(in);
    return x;
    break;
  }
  case 5: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorCopyPredicatedWrapper> x = ptr<OperatorCopyPredicatedWrapper>();
    x->op = CopyPredicated_des(in);
    return x;
    break;
  }
  case 6: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorDmaCopyWrapper> x = ptr<OperatorDmaCopyWrapper>();
    x->op = DmaCopy_des(in);
    return x;
    break;
  }
  case 7: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorDmaTransposeWrapper> x = ptr<OperatorDmaTransposeWrapper>();
    x->op = DmaTranspose_des(in);
    return x;
    break;
  }
  case 8: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorDropoutWrapper> x = ptr<OperatorDropoutWrapper>();
    x->op = Dropout_des(in);
    return x;
    break;
  }
  case 9: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorFindIndex8Wrapper> x = ptr<OperatorFindIndex8Wrapper>();
    x->op = FindIndex8_des(in);
    return x;
    break;
  }
  case 10: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorIotaWrapper> x = ptr<OperatorIotaWrapper>();
    x->op = Iota_des(in);
    return x;
    break;
  }
  case 11: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorLoadMaskRegisterWrapper> x =
        ptr<OperatorLoadMaskRegisterWrapper>();
    x->op = LoadMaskRegister_des(in);
    return x;
    break;
  }
  case 12: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorLoadStationaryWrapper> x = ptr<OperatorLoadStationaryWrapper>();
    x->op = LoadStationary_des(in);
    return x;
    break;
  }
  case 13: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorLocalGatherWrapper> x = ptr<OperatorLocalGatherWrapper>();
    x->op = LocalGather_des(in);
    return x;
    break;
  }
  case 14: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorMatMulWrapper> x = ptr<OperatorMatMulWrapper>();
    x->op = MatMul_des(in);
    return x;
    break;
  }
  case 15: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorMatchReplace8Wrapper> x = ptr<OperatorMatchReplace8Wrapper>();
    x->op = MatchReplace8_des(in);
    return x;
    break;
  }
  case 16: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorMatchValueLoadWrapper> x = ptr<OperatorMatchValueLoadWrapper>();
    x->op = MatchValueLoad_des(in);
    return x;
    break;
  }
  case 17: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorMax8Wrapper> x = ptr<OperatorMax8Wrapper>();
    x->op = Max8_des(in);
    return x;
    break;
  }
  case 18: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorMemSetWrapper> x = ptr<OperatorMemSetWrapper>();
    x->op = MemSet_des(in);
    return x;
    break;
  }
  case 19: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorRangeSelectWrapper> x = ptr<OperatorRangeSelectWrapper>();
    x->op = RangeSelect_des(in);
    return x;
    break;
  }
  case 20: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorReciprocalWrapper> x = ptr<OperatorReciprocalWrapper>();
    x->op = Reciprocal_des(in);
    return x;
    break;
  }
  case 21: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorScalarTensorTensorWrapper> x =
        ptr<OperatorScalarTensorTensorWrapper>();
    x->op = ScalarTensorTensor_des(in);
    return x;
    break;
  }
  case 22: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorShuffleWrapper> x = ptr<OperatorShuffleWrapper>();
    x->op = Shuffle_des(in);
    return x;
    break;
  }
  case 23: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorTensorReduceWrapper> x = ptr<OperatorTensorReduceWrapper>();
    x->op = TensorReduce_des(in);
    return x;
    break;
  }
  case 24: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorTensorTensorScanWrapper> x =
        ptr<OperatorTensorTensorScanWrapper>();
    x->op = TensorTensorScan_des(in);
    return x;
    break;
  }
  case 25: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<OperatorTransposeWrapper> x = ptr<OperatorTransposeWrapper>();
    x->op = Transpose_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<Value> Value_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 101)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ValueVarWrapper> x = ptr<ValueVarWrapper>();
    x->x = String_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ValueBoolWrapper> x = ptr<ValueBoolWrapper>();
    x->value = Bool_des(in);
    return x;
    break;
  }
  case 2: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ValueIntWrapper> x = ptr<ValueIntWrapper>();
    x->value = Int_des(in);
    return x;
    break;
  }
  case 3: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ValueFloatWrapper> x = ptr<ValueFloatWrapper>();
    x->value = Float_des(in);
    return x;
    break;
  }
  case 4: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ValueAccessWrapper> x = ptr<ValueAccessWrapper>();
    x->a = Access_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<Keyword> Keyword_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 102 || c != 0 || l != 2)
    throw std::runtime_error("rror");
  Ptr<Keyword> x = ptr<Keyword>();
  x->name = String_des(in);
  x->value = Value_des(in);
  return x;
}

Ptr<Expr> Expr_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 103)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ExprValueWrapper> x = ptr<ExprValueWrapper>();
    x->v = Value_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 3)
      throw std::runtime_error("rror");
    Ptr<ExprCallWrapper> x = ptr<ExprCallWrapper>();
    x->f = String_des(in);
    x->args = List_Value_des(in);
    x->kwargs = List_Keyword_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<Stmt> Stmt_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 104)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<StmtRetWrapper> x = ptr<StmtRetWrapper>();
    x->v = Value_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 2)
      throw std::runtime_error("rror");
    Ptr<StmtAssignWrapper> x = ptr<StmtAssignWrapper>();
    x->x = String_des(in);
    x->e = Expr_des(in);
    return x;
    break;
  }
  case 2: {
    if (l != 3)
      throw std::runtime_error("rror");
    Ptr<StmtStoreWrapper> x = ptr<StmtStoreWrapper>();
    x->dst = Access_des(in);
    x->op = Operator_des(in);
    x->args = List_Value_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}

Ptr<Kernel> Kernel_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 105 || c != 0 || l != 4)
    throw std::runtime_error("rror");
  Ptr<Kernel> x = ptr<Kernel>();
  x->name = String_des(in);
  x->inputs = List_TensorArg_des(in);
  x->outputs = List_TensorArg_des(in);
  x->body = List_Stmt_des(in);
  return x;
}

List<Ptr<Index>> List_Index_des(FILE *in) {
  List<Ptr<Index>> x;
  return x;
}

List<Ptr<APPair>> List_APPair_des(FILE *in) {
  List<Ptr<APPair>> x;
  return x;
}

Option<TensorSubDim> Option_TensorSubDim_des(FILE *in) {
  Option<TensorSubDim> x;
  return x;
}

List<Ptr<Value>> List_Value_des(FILE *in) {
  List<Ptr<Value>> x;
  return x;
}

List<Ptr<Keyword>> List_Keyword_des(FILE *in) {
  List<Ptr<Keyword>> x;
  return x;
}

List<Ptr<TensorArg>> List_TensorArg_des(FILE *in) {
  List<Ptr<TensorArg>> x;
  return x;
}

List<Ptr<Stmt>> List_Stmt_des(FILE *in) {
  List<Ptr<Stmt>> x;
  return x;
}

Ptr<KLRFile> KLRFile_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 217 || c != 247 || l != 3)
    throw std::runtime_error("rror");
  Ptr<KLRFile> x = ptr<KLRFile>();
  x->major = Nat_des(in);
  x->minor = Nat_des(in);
  x->patch = Nat_des(in);
  return x;
}

Ptr<KLRMetaData> KLRMetaData_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 235 || c != 0 || l != 1)
    throw std::runtime_error("rror");
  Ptr<KLRMetaData> x = ptr<KLRMetaData>();
  x->format = String_des(in);
  return x;
}

Ptr<Contents> Contents_des(FILE *in) {
  u8 t, c, l;
  if (!deserialize_tag(in, &t, &c, &l))
    throw std::runtime_error("rror");
  if (t != 236)
    throw std::runtime_error("rror");
  switch (c) {
  case 0: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ContentsPythonWrapper> x = ptr<ContentsPythonWrapper>();
    x->kernel = Kernel_des(in);
    return x;
    break;
  }
  case 1: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ContentsNkiWrapper> x = ptr<ContentsNkiWrapper>();
    x->kernel = Kernel_des(in);
    return x;
    break;
  }
  case 2: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ContentsKlirWrapper> x = ptr<ContentsKlirWrapper>();
    x->kernel = Kernel_des(in);
    return x;
    break;
  }
  case 3: {
    if (l != 1)
      throw std::runtime_error("rror");
    Ptr<ContentsHloWrapper> x = ptr<ContentsHloWrapper>();
    x->name = String_des(in);
    return x;
    break;
  }
  default:
    throw std::runtime_error("rror");
  }
}
} // namespace klr
