/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Written by the KLR Contributors (https://github.com/leanprover/KLR)
*/
#pragma once

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "klir_common.hpp"
#include "klir_ast.hpp"

namespace klr {

// Pretty Print functions for KLR.Core Abstract Syntax

std::string to_string(Pos &PosInstance);

std::string
to_string(ImmediateRegisterWrapper &ImmediateRegisterWrapperInstance);
std::string to_string(ImmediatePointerWrapper &ImmediatePointerWrapperInstance);
std::string to_string(ImmediateIntWrapper &ImmediateIntWrapperInstance);
std::string to_string(ImmediateFloatWrapper &ImmediateFloatWrapperInstance);
std::string to_string(Immediate &ImmediateInstance);

std::string to_string(Memory &MemoryInstance);

std::string to_string(Dtype &DtypeInstance);

std::string to_string(Shape &ShapeInstance);

std::string to_string(Address &AddressInstance);

std::string to_string(TensorName &TensorNameInstance);

std::string to_string(Slice &SliceInstance);

std::string to_string(IndexCoordWrapper &IndexCoordWrapperInstance);
std::string to_string(IndexSliceWrapper &IndexSliceWrapperInstance);
std::string to_string(Index &IndexInstance);

std::string to_string(AccessBasic &AccessBasicInstance);

std::string to_string(APPair &APPairInstance);

std::string to_string(AccessPattern &AccessPatternInstance);

std::string to_string(ScalarOffsetRegWrapper &ScalarOffsetRegWrapperInstance);
std::string to_string(ScalarOffsetAccWrapper &ScalarOffsetAccWrapperInstance);
std::string to_string(ScalarOffset &ScalarOffsetInstance);

std::string to_string(BirAccessPattern &BirAccessPatternInstance);

std::string to_string(AccessSimpleWrapper &AccessSimpleWrapperInstance);
std::string to_string(AccessBasicWrapper &AccessBasicWrapperInstance);
std::string to_string(AccessPatternWrapper &AccessPatternWrapperInstance);
std::string to_string(AccessBirPatternWrapper &AccessBirPatternWrapperInstance);
std::string to_string(Access &AccessInstance);

std::string to_string(TensorHbm &TensorHbmInstance);

std::string to_string(TensorSram &TensorSramInstance);

std::string
to_string(TensorRefAbstractWrapper &TensorRefAbstractWrapperInstance);
std::string to_string(TensorRefSbufWrapper &TensorRefSbufWrapperInstance);
std::string to_string(TensorRefPsumWrapper &TensorRefPsumWrapperInstance);
std::string to_string(TensorRefHbmWrapper &TensorRefHbmWrapperInstance);
std::string
to_string(TensorRefRegisterWrapper &TensorRefRegisterWrapperInstance);
std::string to_string(TensorRef &TensorRefInstance);

std::string to_string(MatmulPerfMode &MatmulPerfModeInstance);

std::string to_string(Engine &EngineInstance);

std::string
to_string(ActivationImmRegisterWrapper &ActivationImmRegisterWrapperInstance);
std::string
to_string(ActivationImmPointerWrapper &ActivationImmPointerWrapperInstance);
std::string
to_string(ActivationImmFloatWrapper &ActivationImmFloatWrapperInstance);
std::string to_string(ActivationImm &ActivationImmInstance);

std::string to_string(OperandImmWrapper &OperandImmWrapperInstance);
std::string to_string(OperandTileWrapper &OperandTileWrapperInstance);
std::string to_string(Operand &OperandInstance);

std::string to_string(DataPattern &DataPatternInstance);

std::string to_string(AluOp &AluOpInstance);

std::string to_string(DropoutThresholdType &DropoutThresholdTypeInstance);

std::string to_string(AccumCmd &AccumCmdInstance);

std::string to_string(ActivationFunc &ActivationFuncInstance);

std::string to_string(AffineSelectCmp &AffineSelectCmpInstance);

std::string to_string(DgeComputeOp &DgeComputeOpInstance);

std::string to_string(DmaBoundsSkipWrapper &DmaBoundsSkipWrapperInstance);
std::string to_string(DmaBoundsErrorWrapper &DmaBoundsErrorWrapperInstance);
std::string to_string(DmaBoundsRegWrapper &DmaBoundsRegWrapperInstance);
std::string to_string(DmaBounds &DmaBoundsInstance);

std::string to_string(MatmulGroupElement &MatmulGroupElementInstance);

std::string
to_string(IndexMissBehaviorImmWrapper &IndexMissBehaviorImmWrapperInstance);
std::string
to_string(IndexMissBehaviorSkipWrapper &IndexMissBehaviorSkipWrapperInstance);
std::string to_string(IndexMissBehavior &IndexMissBehaviorInstance);

std::string to_string(TensorScalarReverseOps &TensorScalarReverseOpsInstance);

std::string to_string(TensorSubDim &TensorSubDimInstance);

std::string to_string(TransposeOps &TransposeOpsInstance);

std::string to_string(Dropout &DropoutInstance);

std::string to_string(Activate &ActivateInstance);

std::string to_string(AffineSelect &AffineSelectInstance);

std::string to_string(DmaCopy &DmaCopyInstance);

std::string to_string(DmaTranspose &DmaTransposeInstance);

std::string to_string(Transpose &TransposeInstance);

std::string to_string(LoadMaskRegister &LoadMaskRegisterInstance);

std::string to_string(Shuffle &ShuffleInstance);

std::string to_string(MemSet &MemSetInstance);

std::string to_string(Iota &IotaInstance);

std::string to_string(LoadStationary &LoadStationaryInstance);

std::string to_string(MatMul &MatMulInstance);

std::string to_string(LocalGather &LocalGatherInstance);

std::string to_string(RangeSelect &RangeSelectInstance);

std::string to_string(ScalarTensorTensor &ScalarTensorTensorInstance);

std::string to_string(CopyPredicated &CopyPredicatedInstance);

std::string to_string(TensorTensorScan &TensorTensorScanInstance);

std::string to_string(MatchValueLoad &MatchValueLoadInstance);

std::string to_string(FindIndex8 &FindIndex8Instance);

std::string to_string(MatchReplace8 &MatchReplace8Instance);

std::string to_string(Max8 &Max8Instance);

std::string to_string(BatchNormAggregate &BatchNormAggregateInstance);

std::string to_string(BatchNormStats &BatchNormStatsInstance);

std::string to_string(Reciprocal &ReciprocalInstance);

std::string to_string(Copy &CopyInstance);

std::string to_string(TensorReduce &TensorReduceInstance);

std::string to_string(TensorScalar &TensorScalarInstance);

std::string to_string(TensorTensor &TensorTensorInstance);

std::string to_string(NcMatMul &NcMatMulInstance);

std::string to_string(TensorScalarReduce &TensorScalarReduceInstance);

std::string to_string(TensorPartitionReduce &TensorPartitionReduceInstance);

std::string to_string(NcActivate &NcActivateInstance);

std::string to_string(NcAffineSelect &NcAffineSelectInstance);

std::string to_string(NcDmaCopy &NcDmaCopyInstance);

std::string to_string(NcLocalGather &NcLocalGatherInstance);

std::string to_string(NcRangeSelect &NcRangeSelectInstance);

std::string to_string(NcScalarTensorTensor &NcScalarTensorTensorInstance);

std::string to_string(NcCopy &NcCopyInstance);

std::string to_string(SelectReduce &SelectReduceInstance);

std::string to_string(SequenceBounds &SequenceBoundsInstance);

std::string to_string(SendRecv &SendRecvInstance);

std::string to_string(SendRecvCompute &SendRecvComputeInstance);

std::string to_string(QuantizeMX &QuantizeMXInstance);

std::string to_string(MatMulMX &MatMulMXInstance);

std::string to_string(DmaCompute &DmaComputeInstance);

std::string to_string(
    ReplicaGroupUnspecifiedWrapper &ReplicaGroupUnspecifiedWrapperInstance);
std::string
to_string(ReplicaGroupNamedWrapper &ReplicaGroupNamedWrapperInstance);
std::string
to_string(ReplicaGroupLiteralWrapper &ReplicaGroupLiteralWrapperInstance);
std::string to_string(ReplicaGroup &ReplicaGroupInstance);

std::string to_string(CollectiveOp &CollectiveOpInstance);

std::string to_string(RankId &RankIdInstance);

std::string to_string(CurrentProcessingRankId &CurrentProcessingRankIdInstance);

std::string to_string(Send &SendInstance);

std::string to_string(Recv &RecvInstance);

std::string to_string(BrCmpOp &BrCmpOpInstance);

std::string to_string(TensorLoad &TensorLoadInstance);

std::string to_string(TensorStore &TensorStoreInstance);

std::string to_string(RegisterMove &RegisterMoveInstance);

std::string to_string(CmpBranch &CmpBranchInstance);

std::string to_string(RegisterAluOp &RegisterAluOpInstance);

std::string to_string(CoreBarrier &CoreBarrierInstance);

std::string to_string(Rng &RngInstance);

std::string to_string(Rand2 &Rand2Instance);

std::string to_string(RandGetState &RandGetStateInstance);

std::string to_string(SetRngSeed &SetRngSeedInstance);

std::string to_string(RandSetState &RandSetStateInstance);

std::string to_string(ExtendedInst &ExtendedInstInstance);

std::string to_string(TensorScalarCumulative &TensorScalarCumulativeInstance);

std::string to_string(NcNGather &NcNGatherInstance);

std::string to_string(NonzeroWithCount &NonzeroWithCountInstance);

std::string to_string(PrintOutputBuffer &PrintOutputBufferInstance);

std::string to_string(DevicePrint &DevicePrintInstance);

std::string to_string(Exponential &ExponentialInstance);

std::string to_string(OperatorActivateWrapper &OperatorActivateWrapperInstance);
std::string
to_string(OperatorNcActivateWrapper &OperatorNcActivateWrapperInstance);
std::string to_string(
    OperatorActivationReduceWrapper &OperatorActivationReduceWrapperInstance);
std::string
to_string(OperatorAffineSelectWrapper &OperatorAffineSelectWrapperInstance);
std::string
to_string(OperatorNcAffineSelectWrapper &OperatorNcAffineSelectWrapperInstance);
std::string to_string(OperatorBatchNormAggregateWrapper
                          &OperatorBatchNormAggregateWrapperInstance);
std::string
to_string(OperatorBatchNormStatsWrapper &OperatorBatchNormStatsWrapperInstance);
std::string to_string(OperatorCopyWrapper &OperatorCopyWrapperInstance);
std::string to_string(OperatorNcCopyWrapper &OperatorNcCopyWrapperInstance);
std::string
to_string(OperatorCopyPredicatedWrapper &OperatorCopyPredicatedWrapperInstance);
std::string to_string(OperatorDmaCopyWrapper &OperatorDmaCopyWrapperInstance);
std::string
to_string(OperatorNcDmaCopyWrapper &OperatorNcDmaCopyWrapperInstance);
std::string
to_string(OperatorDmaTransposeWrapper &OperatorDmaTransposeWrapperInstance);
std::string to_string(OperatorDropoutWrapper &OperatorDropoutWrapperInstance);
std::string
to_string(OperatorFindIndex8Wrapper &OperatorFindIndex8WrapperInstance);
std::string to_string(OperatorIotaWrapper &OperatorIotaWrapperInstance);
std::string to_string(
    OperatorLoadMaskRegisterWrapper &OperatorLoadMaskRegisterWrapperInstance);
std::string
to_string(OperatorLoadStationaryWrapper &OperatorLoadStationaryWrapperInstance);
std::string
to_string(OperatorLocalGatherWrapper &OperatorLocalGatherWrapperInstance);
std::string
to_string(OperatorNcLocalGatherWrapper &OperatorNcLocalGatherWrapperInstance);
std::string to_string(OperatorMatMulWrapper &OperatorMatMulWrapperInstance);
std::string to_string(OperatorNcMatMulWrapper &OperatorNcMatMulWrapperInstance);
std::string
to_string(OperatorMatchReplace8Wrapper &OperatorMatchReplace8WrapperInstance);
std::string
to_string(OperatorMatchValueLoadWrapper &OperatorMatchValueLoadWrapperInstance);
std::string to_string(OperatorMax8Wrapper &OperatorMax8WrapperInstance);
std::string to_string(OperatorMemSetWrapper &OperatorMemSetWrapperInstance);
std::string
to_string(OperatorRangeSelectWrapper &OperatorRangeSelectWrapperInstance);
std::string
to_string(OperatorNcRangeSelectWrapper &OperatorNcRangeSelectWrapperInstance);
std::string
to_string(OperatorReciprocalWrapper &OperatorReciprocalWrapperInstance);
std::string to_string(OperatorScalarTensorTensorWrapper
                          &OperatorScalarTensorTensorWrapperInstance);
std::string to_string(OperatorNcScalarTensorTensorWrapper
                          &OperatorNcScalarTensorTensorWrapperInstance);
std::string to_string(OperatorShuffleWrapper &OperatorShuffleWrapperInstance);
std::string
to_string(OperatorTensorReduceWrapper &OperatorTensorReduceWrapperInstance);
std::string
to_string(OperatorTensorScalarWrapper &OperatorTensorScalarWrapperInstance);
std::string
to_string(OperatorTensorTensorWrapper &OperatorTensorTensorWrapperInstance);
std::string to_string(
    OperatorTensorTensorScanWrapper &OperatorTensorTensorScanWrapperInstance);
std::string to_string(OperatorTensorPartitionReduceWrapper
                          &OperatorTensorPartitionReduceWrapperInstance);
std::string to_string(OperatorTensorScalarReduceWrapper
                          &OperatorTensorScalarReduceWrapperInstance);
std::string
to_string(OperatorTransposeWrapper &OperatorTransposeWrapperInstance);
std::string
to_string(OperatorSelectReduceWrapper &OperatorSelectReduceWrapperInstance);
std::string
to_string(OperatorSequenceBoundsWrapper &OperatorSequenceBoundsWrapperInstance);
std::string to_string(OperatorSendRecvWrapper &OperatorSendRecvWrapperInstance);
std::string to_string(
    OperatorSendRecvComputeWrapper &OperatorSendRecvComputeWrapperInstance);
std::string
to_string(OperatorTensorLoadWrapper &OperatorTensorLoadWrapperInstance);
std::string
to_string(OperatorTensorStoreWrapper &OperatorTensorStoreWrapperInstance);
std::string
to_string(OperatorRegisterMoveWrapper &OperatorRegisterMoveWrapperInstance);
std::string
to_string(OperatorCmpBranchWrapper &OperatorCmpBranchWrapperInstance);
std::string
to_string(OperatorRegisterAluOpWrapper &OperatorRegisterAluOpWrapperInstance);
std::string
to_string(OperatorQuantizeMXWrapper &OperatorQuantizeMXWrapperInstance);
std::string
to_string(OperatorNcMatMulMXWrapper &OperatorNcMatMulMXWrapperInstance);
std::string
to_string(OperatorDmaComputeWrapper &OperatorDmaComputeWrapperInstance);
std::string
to_string(OperatorAllReduceWrapper &OperatorAllReduceWrapperInstance);
std::string
to_string(OperatorAllGatherWrapper &OperatorAllGatherWrapperInstance);
std::string
to_string(OperatorReduceScatterWrapper &OperatorReduceScatterWrapperInstance);
std::string to_string(
    OperatorCollectivePermuteWrapper &OperatorCollectivePermuteWrapperInstance);
std::string to_string(OperatorCollectivePermuteImplicitWrapper
                          &OperatorCollectivePermuteImplicitWrapperInstance);
std::string
to_string(OperatorCollectivePermuteImplicitReduceWrapper
              &OperatorCollectivePermuteImplicitReduceWrapperInstance);
std::string
to_string(OperatorBroadcastWrapper &OperatorBroadcastWrapperInstance);
std::string to_string(OperatorAllToAllWrapper &OperatorAllToAllWrapperInstance);
std::string to_string(OperatorRankIdWrapper &OperatorRankIdWrapperInstance);
std::string to_string(OperatorCurrentProcessingRankIdWrapper
                          &OperatorCurrentProcessingRankIdWrapperInstance);
std::string to_string(OperatorSendWrapper &OperatorSendWrapperInstance);
std::string to_string(OperatorRecvWrapper &OperatorRecvWrapperInstance);
std::string
to_string(OperatorCoreBarrierWrapper &OperatorCoreBarrierWrapperInstance);
std::string to_string(OperatorRngWrapper &OperatorRngWrapperInstance);
std::string to_string(OperatorRand2Wrapper &OperatorRand2WrapperInstance);
std::string
to_string(OperatorRandGetStateWrapper &OperatorRandGetStateWrapperInstance);
std::string
to_string(OperatorSetRngSeedWrapper &OperatorSetRngSeedWrapperInstance);
std::string
to_string(OperatorRandSetStateWrapper &OperatorRandSetStateWrapperInstance);
std::string
to_string(OperatorExtendedInstWrapper &OperatorExtendedInstWrapperInstance);
std::string to_string(OperatorTensorScalarCumulativeWrapper
                          &OperatorTensorScalarCumulativeWrapperInstance);
std::string
to_string(OperatorNcNGatherWrapper &OperatorNcNGatherWrapperInstance);
std::string to_string(
    OperatorNonzeroWithCountWrapper &OperatorNonzeroWithCountWrapperInstance);
std::string
to_string(OperatorDevicePrintWrapper &OperatorDevicePrintWrapperInstance);
std::string
to_string(OperatorExponentialWrapper &OperatorExponentialWrapperInstance);
std::string to_string(Operator &OperatorInstance);

std::string to_string(StmtOperWrapper &StmtOperWrapperInstance);
std::string to_string(Stmt &StmtInstance);

std::string to_string(Block &BlockInstance);

std::string to_string(Kernel &KernelInstance);

std::string to_string(SharedConstantFile &SharedConstantFileInstance);

std::string to_string(Edges &EdgesInstance);

std::string to_string(LncKernel &LncKernelInstance);

std::string to_string(KLRFile &KLRFileInstance);

std::string to_string(KLRMetaData &KLRMetaDataInstance);

std::string to_string(ContentsPythonWrapper &ContentsPythonWrapperInstance);
std::string to_string(ContentsNkiWrapper &ContentsNkiWrapperInstance);
std::string to_string(ContentsKernelWrapper &ContentsKernelWrapperInstance);
std::string to_string(ContentsLncWrapper &ContentsLncWrapperInstance);
std::string to_string(ContentsHloWrapper &ContentsHloWrapperInstance);
std::string to_string(Contents &ContentsInstance);
} // namespace klr
