/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Written by the KLR Contributors (https://github.com/leanprover/KLR)
*/
#pragma once

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "klir_common.hpp"
#include "klir_ast.hpp"

namespace klr {

List<Bool> List_Bool_des(FILE *in);
List<Nat> List_Nat_des(FILE *in);
List<Int> List_Int_des(FILE *in);
List<Float> List_Float_des(FILE *in);
List<String> List_String_des(FILE *in);
Option<Bool> Option_Bool_des(FILE *in);
Option<Nat> Option_Nat_des(FILE *in);
Option<Int> Option_Int_des(FILE *in);
Option<Float> Option_Float_des(FILE *in);
Option<String> Option_String_des(FILE *in);
Ptr<Pos> Pos_des(FILE *in);
Memory Memory_des(FILE *in);
Dtype Dtype_des(FILE *in);
Ptr<Shape> Shape_des(FILE *in);
Ptr<Address> Address_des(FILE *in);
Ptr<TensorSram> TensorSram_des(FILE *in);
Ptr<Slice> Slice_des(FILE *in);
Ptr<Index> Index_des(FILE *in);
Ptr<AccessBasic> AccessBasic_des(FILE *in);
Ptr<APPair> APPair_des(FILE *in);
Ptr<AccessPattern> AccessPattern_des(FILE *in);
Ptr<Access> Access_des(FILE *in);
Ptr<TensorHbm> TensorHbm_des(FILE *in);
ParQuadrant ParQuadrant_des(FILE *in);
Ptr<TensorView> TensorView_des(FILE *in);
Ptr<TensorRef> TensorRef_des(FILE *in);
Ptr<TensorArg> TensorArg_des(FILE *in);
Engine Engine_des(FILE *in);
Ptr<Immediate> Immediate_des(FILE *in);
Ptr<ActivationImm> ActivationImm_des(FILE *in);
Ptr<DataPattern> DataPattern_des(FILE *in);
AluOp AluOp_des(FILE *in);
DropoutThresholdType DropoutThresholdType_des(FILE *in);
AccumCmd AccumCmd_des(FILE *in);
ActivationFunc ActivationFunc_des(FILE *in);
AffineSelectCmp AffineSelectCmp_des(FILE *in);
DgeComputeOp DgeComputeOp_des(FILE *in);
Ptr<DmaBounds> DmaBounds_des(FILE *in);
MatmulGroupElement MatmulGroupElement_des(FILE *in);
Ptr<IndexMissBehavior> IndexMissBehavior_des(FILE *in);
TensorScalarReverseOps TensorScalarReverseOps_des(FILE *in);
TensorSubDim TensorSubDim_des(FILE *in);
Ptr<Dropout> Dropout_des(FILE *in);
Ptr<Activate> Activate_des(FILE *in);
Ptr<AffineSelect> AffineSelect_des(FILE *in);
Ptr<DmaCopy> DmaCopy_des(FILE *in);
Ptr<DmaHbmLoad> DmaHbmLoad_des(FILE *in);
Ptr<DmaHbmStore> DmaHbmStore_des(FILE *in);
Ptr<DmaTranspose> DmaTranspose_des(FILE *in);
Ptr<Transpose> Transpose_des(FILE *in);
Ptr<LoadMaskRegister> LoadMaskRegister_des(FILE *in);
Ptr<Shuffle> Shuffle_des(FILE *in);
Ptr<MemSet> MemSet_des(FILE *in);
Ptr<Iota> Iota_des(FILE *in);
Ptr<LoadStationary> LoadStationary_des(FILE *in);
Ptr<MatMul> MatMul_des(FILE *in);
Ptr<LocalGather> LocalGather_des(FILE *in);
Ptr<RangeSelect> RangeSelect_des(FILE *in);
Ptr<ScalarTensorTensor> ScalarTensorTensor_des(FILE *in);
Ptr<CopyPredicated> CopyPredicated_des(FILE *in);
Ptr<TensorTensorScan> TensorTensorScan_des(FILE *in);
Ptr<MatchValueLoad> MatchValueLoad_des(FILE *in);
Ptr<FindIndex8> FindIndex8_des(FILE *in);
Ptr<MatchReplace8> MatchReplace8_des(FILE *in);
Ptr<Max8> Max8_des(FILE *in);
Ptr<BatchNormAggregate> BatchNormAggregate_des(FILE *in);
Ptr<BatchNormStats> BatchNormStats_des(FILE *in);
Ptr<Reciprocal> Reciprocal_des(FILE *in);
Ptr<Copy> Copy_des(FILE *in);
Ptr<TensorReduce> TensorReduce_des(FILE *in);
Ptr<TensorScalar> TensorScalar_des(FILE *in);
Ptr<TensorTensor> TensorTensor_des(FILE *in);
Ptr<Operator> Operator_des(FILE *in);
Ptr<Value> Value_des(FILE *in);
Ptr<Keyword> Keyword_des(FILE *in);
Ptr<Expr> Expr_des(FILE *in);
Ptr<Stmt> Stmt_des(FILE *in);
Ptr<Kernel> Kernel_des(FILE *in);
List<Ptr<Index>> List_Index_des(FILE *in);
List<Ptr<APPair>> List_APPair_des(FILE *in);
Option<TensorSubDim> Option_TensorSubDim_des(FILE *in);
List<Ptr<Value>> List_Value_des(FILE *in);
List<Ptr<Keyword>> List_Keyword_des(FILE *in);
List<Ptr<TensorSram>> List_TensorSram_des(FILE *in);
List<Ptr<Stmt>> List_Stmt_des(FILE *in);
Ptr<KLRFile> KLRFile_des(FILE *in);
Ptr<KLRMetaData> KLRMetaData_des(FILE *in);
Ptr<Contents> Contents_des(FILE *in);
} // namespace klr
