/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Govereau, Sean McLaughlin
*/
#pragma once

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "stdc.h"
#include "region.h"
#include "ast_common.h"
#include "ast_klir.h"

bool Core_Memory_ser(FILE *out, enum Core_Memory x);
bool Core_Dtype_ser(FILE *out, enum Core_Dtype x);
bool Core_Shape_ser(FILE *out, struct Core_Shape *x);
bool Core_Address_ser(FILE *out, struct Core_Address *x);
bool Core_TensorName_ser(FILE *out, struct Core_TensorName *x);
bool Core_Slice_ser(FILE *out, struct Core_Slice *x);
bool Core_Index_ser(FILE *out, struct Core_Index *x);
bool Core_AccessBasic_ser(FILE *out, struct Core_AccessBasic *x);
bool Core_APPair_ser(FILE *out, struct Core_APPair *x);
bool Core_AccessPattern_ser(FILE *out, struct Core_AccessPattern *x);
bool Core_Access_ser(FILE *out, struct Core_Access *x);
bool Core_TensorHbm_ser(FILE *out, struct Core_TensorHbm *x);
bool Core_ParQuadrant_ser(FILE *out, enum Core_ParQuadrant x);
bool Core_TensorSram_ser(FILE *out, struct Core_TensorSram *x);
bool Core_TensorRef_ser(FILE *out, struct Core_TensorRef *x);
bool Core_Engine_ser(FILE *out, enum Core_Engine x);
bool Core_Immediate_ser(FILE *out, struct Core_Immediate *x);
bool Core_ActivationImm_ser(FILE *out, struct Core_ActivationImm *x);
bool Core_DataPattern_ser(FILE *out, struct Core_DataPattern *x);
bool Core_AluOp_ser(FILE *out, enum Core_AluOp x);
bool Core_DropoutThresholdType_ser(FILE *out, enum Core_DropoutThresholdType x);
bool Core_AccumCmd_ser(FILE *out, enum Core_AccumCmd x);
bool Core_ActivationFunc_ser(FILE *out, enum Core_ActivationFunc x);
bool Core_AffineSelectCmp_ser(FILE *out, enum Core_AffineSelectCmp x);
bool Core_DgeComputeOp_ser(FILE *out, enum Core_DgeComputeOp x);
bool Core_DmaBounds_ser(FILE *out, struct Core_DmaBounds *x);
bool Core_MatmulGroupElement_ser(FILE *out, enum Core_MatmulGroupElement x);
bool Core_IndexMissBehavior_ser(FILE *out, struct Core_IndexMissBehavior *x);
bool Core_TensorScalarReverseOps_ser(FILE *out,
                                     enum Core_TensorScalarReverseOps x);
bool Core_TensorSubDim_ser(FILE *out, enum Core_TensorSubDim x);
bool Core_Dropout_ser(FILE *out, struct Core_Dropout *x);
bool Core_Activate_ser(FILE *out, struct Core_Activate *x);
bool Core_AffineSelect_ser(FILE *out, struct Core_AffineSelect *x);
bool Core_DmaCopy_ser(FILE *out, struct Core_DmaCopy *x);
bool Core_DmaTranspose_ser(FILE *out, struct Core_DmaTranspose *x);
bool Core_Transpose_ser(FILE *out, struct Core_Transpose *x);
bool Core_LoadMaskRegister_ser(FILE *out, struct Core_LoadMaskRegister *x);
bool Core_Shuffle_ser(FILE *out, struct Core_Shuffle *x);
bool Core_MemSet_ser(FILE *out, struct Core_MemSet *x);
bool Core_Iota_ser(FILE *out, struct Core_Iota *x);
bool Core_LoadStationary_ser(FILE *out, struct Core_LoadStationary *x);
bool Core_MatMul_ser(FILE *out, struct Core_MatMul *x);
bool Core_LocalGather_ser(FILE *out, struct Core_LocalGather *x);
bool Core_RangeSelect_ser(FILE *out, struct Core_RangeSelect *x);
bool Core_ScalarTensorTensor_ser(FILE *out, struct Core_ScalarTensorTensor *x);
bool Core_CopyPredicated_ser(FILE *out, struct Core_CopyPredicated *x);
bool Core_TensorTensorScan_ser(FILE *out, struct Core_TensorTensorScan *x);
bool Core_MatchValueLoad_ser(FILE *out, struct Core_MatchValueLoad *x);
bool Core_FindIndex8_ser(FILE *out, struct Core_FindIndex8 *x);
bool Core_MatchReplace8_ser(FILE *out, struct Core_MatchReplace8 *x);
bool Core_Max8_ser(FILE *out, struct Core_Max8 *x);
bool Core_BatchNormAggregate_ser(FILE *out, struct Core_BatchNormAggregate *x);
bool Core_BatchNormStats_ser(FILE *out, struct Core_BatchNormStats *x);
bool Core_Reciprocal_ser(FILE *out, struct Core_Reciprocal *x);
bool Core_Copy_ser(FILE *out, struct Core_Copy *x);
bool Core_TensorReduce_ser(FILE *out, struct Core_TensorReduce *x);
bool Core_TensorScalar_ser(FILE *out, struct Core_TensorScalar *x);
bool Core_TensorTensor_ser(FILE *out, struct Core_TensorTensor *x);
bool Core_Operator_ser(FILE *out, struct Core_Operator *x);
bool Core_Value_ser(FILE *out, struct Core_Value *x);
bool Core_Keyword_ser(FILE *out, struct Core_Keyword *x);
bool Core_Expr_ser(FILE *out, struct Core_Expr *x);
bool Core_Stmt_ser(FILE *out, struct Core_Stmt *x);
bool Core_Kernel_ser(FILE *out, struct Core_Kernel *x);
bool Core_Index_List_ser(FILE *out, struct Core_Index_List *x);
bool Core_APPair_List_ser(FILE *out, struct Core_APPair_List *x);
bool Core_TensorSubDim_Option_ser(FILE *out, enum Core_TensorSubDim x);
bool Core_Value_List_ser(FILE *out, struct Core_Value_List *x);
bool Core_Keyword_List_ser(FILE *out, struct Core_Keyword_List *x);
bool Core_TensorName_List_ser(FILE *out, struct Core_TensorName_List *x);
bool Core_Stmt_List_ser(FILE *out, struct Core_Stmt_List *x);

bool Core_Memory_des(FILE *in, struct region *region, enum Core_Memory *x);
bool Core_Dtype_des(FILE *in, struct region *region, enum Core_Dtype *x);
bool Core_Shape_des(FILE *in, struct region *region, struct Core_Shape **x);
bool Core_Address_des(FILE *in, struct region *region, struct Core_Address **x);
bool Core_TensorName_des(FILE *in, struct region *region,
                         struct Core_TensorName **x);
bool Core_Slice_des(FILE *in, struct region *region, struct Core_Slice **x);
bool Core_Index_des(FILE *in, struct region *region, struct Core_Index **x);
bool Core_AccessBasic_des(FILE *in, struct region *region,
                          struct Core_AccessBasic **x);
bool Core_APPair_des(FILE *in, struct region *region, struct Core_APPair **x);
bool Core_AccessPattern_des(FILE *in, struct region *region,
                            struct Core_AccessPattern **x);
bool Core_Access_des(FILE *in, struct region *region, struct Core_Access **x);
bool Core_TensorHbm_des(FILE *in, struct region *region,
                        struct Core_TensorHbm **x);
bool Core_ParQuadrant_des(FILE *in, struct region *region,
                          enum Core_ParQuadrant *x);
bool Core_TensorSram_des(FILE *in, struct region *region,
                         struct Core_TensorSram **x);
bool Core_TensorRef_des(FILE *in, struct region *region,
                        struct Core_TensorRef **x);
bool Core_Engine_des(FILE *in, struct region *region, enum Core_Engine *x);
bool Core_Immediate_des(FILE *in, struct region *region,
                        struct Core_Immediate **x);
bool Core_ActivationImm_des(FILE *in, struct region *region,
                            struct Core_ActivationImm **x);
bool Core_DataPattern_des(FILE *in, struct region *region,
                          struct Core_DataPattern **x);
bool Core_AluOp_des(FILE *in, struct region *region, enum Core_AluOp *x);
bool Core_DropoutThresholdType_des(FILE *in, struct region *region,
                                   enum Core_DropoutThresholdType *x);
bool Core_AccumCmd_des(FILE *in, struct region *region, enum Core_AccumCmd *x);
bool Core_ActivationFunc_des(FILE *in, struct region *region,
                             enum Core_ActivationFunc *x);
bool Core_AffineSelectCmp_des(FILE *in, struct region *region,
                              enum Core_AffineSelectCmp *x);
bool Core_DgeComputeOp_des(FILE *in, struct region *region,
                           enum Core_DgeComputeOp *x);
bool Core_DmaBounds_des(FILE *in, struct region *region,
                        struct Core_DmaBounds **x);
bool Core_MatmulGroupElement_des(FILE *in, struct region *region,
                                 enum Core_MatmulGroupElement *x);
bool Core_IndexMissBehavior_des(FILE *in, struct region *region,
                                struct Core_IndexMissBehavior **x);
bool Core_TensorScalarReverseOps_des(FILE *in, struct region *region,
                                     enum Core_TensorScalarReverseOps *x);
bool Core_TensorSubDim_des(FILE *in, struct region *region,
                           enum Core_TensorSubDim *x);
bool Core_Dropout_des(FILE *in, struct region *region, struct Core_Dropout **x);
bool Core_Activate_des(FILE *in, struct region *region,
                       struct Core_Activate **x);
bool Core_AffineSelect_des(FILE *in, struct region *region,
                           struct Core_AffineSelect **x);
bool Core_DmaCopy_des(FILE *in, struct region *region, struct Core_DmaCopy **x);
bool Core_DmaTranspose_des(FILE *in, struct region *region,
                           struct Core_DmaTranspose **x);
bool Core_Transpose_des(FILE *in, struct region *region,
                        struct Core_Transpose **x);
bool Core_LoadMaskRegister_des(FILE *in, struct region *region,
                               struct Core_LoadMaskRegister **x);
bool Core_Shuffle_des(FILE *in, struct region *region, struct Core_Shuffle **x);
bool Core_MemSet_des(FILE *in, struct region *region, struct Core_MemSet **x);
bool Core_Iota_des(FILE *in, struct region *region, struct Core_Iota **x);
bool Core_LoadStationary_des(FILE *in, struct region *region,
                             struct Core_LoadStationary **x);
bool Core_MatMul_des(FILE *in, struct region *region, struct Core_MatMul **x);
bool Core_LocalGather_des(FILE *in, struct region *region,
                          struct Core_LocalGather **x);
bool Core_RangeSelect_des(FILE *in, struct region *region,
                          struct Core_RangeSelect **x);
bool Core_ScalarTensorTensor_des(FILE *in, struct region *region,
                                 struct Core_ScalarTensorTensor **x);
bool Core_CopyPredicated_des(FILE *in, struct region *region,
                             struct Core_CopyPredicated **x);
bool Core_TensorTensorScan_des(FILE *in, struct region *region,
                               struct Core_TensorTensorScan **x);
bool Core_MatchValueLoad_des(FILE *in, struct region *region,
                             struct Core_MatchValueLoad **x);
bool Core_FindIndex8_des(FILE *in, struct region *region,
                         struct Core_FindIndex8 **x);
bool Core_MatchReplace8_des(FILE *in, struct region *region,
                            struct Core_MatchReplace8 **x);
bool Core_Max8_des(FILE *in, struct region *region, struct Core_Max8 **x);
bool Core_BatchNormAggregate_des(FILE *in, struct region *region,
                                 struct Core_BatchNormAggregate **x);
bool Core_BatchNormStats_des(FILE *in, struct region *region,
                             struct Core_BatchNormStats **x);
bool Core_Reciprocal_des(FILE *in, struct region *region,
                         struct Core_Reciprocal **x);
bool Core_Copy_des(FILE *in, struct region *region, struct Core_Copy **x);
bool Core_TensorReduce_des(FILE *in, struct region *region,
                           struct Core_TensorReduce **x);
bool Core_TensorScalar_des(FILE *in, struct region *region,
                           struct Core_TensorScalar **x);
bool Core_TensorTensor_des(FILE *in, struct region *region,
                           struct Core_TensorTensor **x);
bool Core_Operator_des(FILE *in, struct region *region,
                       struct Core_Operator **x);
bool Core_Value_des(FILE *in, struct region *region, struct Core_Value **x);
bool Core_Keyword_des(FILE *in, struct region *region, struct Core_Keyword **x);
bool Core_Expr_des(FILE *in, struct region *region, struct Core_Expr **x);
bool Core_Stmt_des(FILE *in, struct region *region, struct Core_Stmt **x);
bool Core_Kernel_des(FILE *in, struct region *region, struct Core_Kernel **x);
bool Core_Index_List_des(FILE *in, struct region *region,
                         struct Core_Index_List **x);
bool Core_APPair_List_des(FILE *in, struct region *region,
                          struct Core_APPair_List **x);
bool Core_TensorSubDim_Option_des(FILE *in, struct region *region,
                                  enum Core_TensorSubDim *x);
bool Core_Value_List_des(FILE *in, struct region *region,
                         struct Core_Value_List **x);
bool Core_Keyword_List_des(FILE *in, struct region *region,
                           struct Core_Keyword_List **x);
bool Core_TensorName_List_des(FILE *in, struct region *region,
                              struct Core_TensorName_List **x);
bool Core_Stmt_List_des(FILE *in, struct region *region,
                        struct Core_Stmt_List **x);
