# Do not rename this file. It is used by name in the trusted publisher section
# in pypi.org and test.pypi.org

name: CI

on:
  push:
    branches:
    - '**' # For now, let's build all branches. Roll this back if it gets too slow or we exhaust our quota.
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # Build v1.2.3 tags as well. We'll use tags as the criteria for publishing
  # As long as we're building on all branch pushes, we do not need to run on pull requests.
  # If we stop that in the future, we'll want this back, so leaving in commented code.
  # pull_request:
  #   branches:
  #   - '**' # * does not match '/' like sm/my-feature
  workflow_dispatch: # For manually triggering a build: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        # We mainly care about hardware rather than OS
        # macos-13 is x64
        # macos-latest is arm64
        # ubuntu-latest is x64
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install C libraries on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libarchive-dev

      - name: Install C libraries on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install zlib libarchive

      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "KLR/Util/Gzip"

      # Build (and test) Lean. Tests are all via #guard macros
      # now so you can't really build without testing.
      - uses: leanprover/lean-action@v1
        # Leaving in this workaround for some spurious crashes during the build, due to a bug in lean-action,
        # in case it's not really fixed.
        # https://github.com/leanprover/lean-action/issues/116#issuecomment-2663316227
        # with:
        #   use-github-cache: false

      - name: Run Lean tests
        run: lake exe klr

      - name: List library dependencies
        run: ./bin/check-libs ./.lake/build/bin/klr
